MiniDeps.add("echasnovski/mini.pick")
MiniDeps.later(function()
    require("mini.pick").setup({})

    vim.keymap.set("n", "<leader><leader>", function()
        MiniPick.builtin.files()
    end, { desc = "Files in rootdir" })
    vim.keymap.set("n", "<leader>/", function()
        MiniPick.builtin.grep_live()
    end, { desc = "Live grep" })
    vim.keymap.set("n", "<leader>,", function()
        MiniPick.builtin.buffers()
    end, { desc = "Open buffers" })
    vim.keymap.set("n", "<leader>g/", function()
        MiniPick.builtin.files({ items = { "foo", "bar" } })
    end, { desc = "Changed files " })
end)
