vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
end
vim.g.colors_name = "aqua"

local palette = require("palette")
local M = {}

M.apply_highlight = function()
    for _, hl_group in pairs(M.all_highlights) do
        for hl, setting in pairs(hl_group) do
            vim.api.nvim_set_hl(0, hl, setting)
        end
    end
end

M.all_highlights = {

    flash = {
        FlashBackdrop = { link = "Comment" },
        FlashMatch = { link = "Search" },
        FlashCurrent = { link = "IncSearch" },
        FlashLabel = { fg = palette.dark.black, bg = palette.ansi.red, bold = true },
        FlashPrompt = { link = "MsgArea" },
        FlashPromptIcon = { link = "Special" },
        FlashCursor = { link = "Cursor" },
    },

    common = {
        -- Remaining individual set_hl calls
        NotifyERRORTitle = { fg = palette.brights.red },
        NotifyWARNTitle = { fg = palette.ansi.red },
        NotifyINFOTitle = { fg = palette.brights.green },
        NotifyDEBUGTitle = { fg = palette.brights.white },
        NotifyTRACETitle = { fg = palette.dark.magenta },
        NotifyERRORIcon = { link = "NotifyERRORTitle" },
        NotifyWARNIcon = { link = "NotifyWARNTitle" },
        NotifyINFOIcon = { link = "NotifyINFOTitle" },
        NotifyDEBUGIcon = { link = "NotifyDEBUGTitle" },
        NotifyTRACEIcon = { link = "NotifyTRACETitle" },
        NotifyERRORBorder = { link = "NotifyERRORTitle" },
        NotifyWARNBorder = { link = "NotifyWARNTitle" },
        NotifyINFOBorder = { link = "NotifyINFOTitle" },
        NotifyDEBUGBorder = { link = "NotifyDEBUGTitle" },
        NotifyTRACEBorder = { link = "NotifyTRACETitle" },
        NotifyERRORBody = { link = "NotifyERRORTitle" },
        NotifyWARNBody = { link = "NotifyWARNTitle" },
        NotifyINFOBody = { link = "NotifyINFOTitle" },
        NotifyDEBUGBody = { link = "NotifyDEBUGTitle" },
        NotifyTRACEBody = { link = "NotifyTRACETitle" },
        NvimTreeNormal = { link = "NormalSB" },
        NvimTreeEndOfBuffer = { fg = palette.normal },
        NvimTreeRootFolder = { bold = true, fg = palette.brights.white },
        NvimTreeGitDirty = { fg = palette.dark.yellow },
        NvimTreeGitNew = { fg = palette.brights.green },
        NvimTreeGitRenamed = { fg = palette.dark.magenta },
        NvimTreeGitDeleted = { fg = palette.brights.red },
        NvimTreeGitIgnored = { fg = palette.brights.black },
        NvimTreeSpecialFile = { underline = true, fg = palette.ansi.yellow },
        NvimTreeIndentMarker = { fg = palette.brights.black },
        NvimTreeImageFile = { fg = palette.ansi.yellow },
        NvimTreeSymlink = { fg = palette.dark.magenta },
        NvimTreeFolderName = { fg = palette.brights.white },
        NvimTreeOpenedFolderName = { bold = true, fg = palette.brights.white },
        NvimTreeOpenedFile = { fg = palette.brights.blue },
        diffAdded = { link = "Added" },
        diffRemoved = { link = "Removed" },
        diffChanged = { link = "Changed" },
        htmlTag = { fg = palette.ansi.blue },
        NONE = {},
        TreesitterContext = { bg = palette.extra.gray0 },
        WhichKeyGroup = { link = "Function" },
        WhichKeySeperator = { link = "Comment" },
        WhichKeySeparator = { link = "Comment" },
        WhichKeyValue = { link = "Comment" },
        FidgetTitle = { link = "Title" },
        Bold = { bold = true },
        GitGutterAdd = { fg = palette.brights.green },
        GitGutterChange = { fg = palette.dark.yellow },
        GitGutterDelete = { fg = palette.brights.red },
        LspTroubleText = { fg = palette.normal },
        LspTroubleCount = { fg = palette.brights.magenta, bg = palette.brights.black },
        LspTroubleNormal = { fg = palette.brights.black, bg = palette.extra.gray2 },
        xmlTagName = { link = "htmlTag" },
        cssMedia = { link = "Keyword" },
        cssProp = { link = "Constant" },
        cssPseudoClassId = { link = "Function" },
        lessAmpersand = { link = "Function" },
        lessClass = { link = "Function" },
        lessClassCall = { link = "Function" },
        lessCssAttribute = { link = "Constant" },
        lessFunction = { link = "Constant" },
        lessVariable = { fg = palette.brights.white },
        diffOldFile = { fg = palette.ansi.yellow },
        diffIndexLine = { fg = palette.normal },
        jsonKeyword = { fg = palette.ansi.blue },
        jsonNull = { link = "Constant" },
        luaFunction = { link = "Keyword" },
        luaTable = {},
        yamlBlockMappingKey = { fg = palette.ansi.blue },
        yamlFlowMappingKey = { fg = palette.ansi.blue },
        CmpItemAbbr = { fg = palette.brights.white },
        CmpItemAbbrDeprecated = { strikethrough = true, fg = palette.normal },
        CmpItemAbbrMatch = { fg = palette.ansi.cyan },
        CmpItemAbbrMatchFuzzy = { fg = palette.ansi.cyan },
        CmpItemKindDefault = { fg = palette.dark.black },
        CmpItemMenu = { link = "Comment" },
        CmpItemKindKeyword = { link = "Keyword" },
        CmpItemKindVariable = { link = "@variable" },
        CmpItemKindConstant = { link = "@constant" },
        CmpItemKindReference = { link = "Keyword" },
        CmpItemKindValue = { link = "Keyword" },
        CmpItemKindFunction = { link = "Function" },
        CmpItemKindMethod = { link = "Function" },
        CmpItemKindConstructor = { link = "@constructor" },
        CmpItemKindInterface = { link = "Constant" },
        CmpItemKindEvent = { link = "Constant" },
        CmpItemKindEnum = { link = "Constant" },
        CmpItemKindUnit = { link = "Constant" },
        CmpItemKindClass = { link = "Type" },
        CmpItemKindStruct = { link = "Type" },
        CmpItemKindModule = { link = "@module" },
        CmpItemKindProperty = { link = "@property" },
        CmpItemKindField = { link = "@variable.member" },
        CmpItemKindTypeParameter = { link = "@variable.member" },
        CmpItemKindEnumMember = { link = "@variable.member" },
        CmpItemKindOperator = { link = "Operator" },
        CmpItemKindSnippet = { fg = palette.normal },
        CocInlayHint = { fg = palette.brights.black, bg = none },
        CocExplorerNormalFloat = { link = "NormalSB" },
        CocExplorerFileRootName = { bold = true, fg = palette.brights.white },
        CocExplorerFileDirectory = { bold = true, fg = palette.brights.white },
        CocExplorerGitPathChange_Internal = { fg = palette.dark.magenta },
        CocExplorerGitAdded = { fg = palette.brights.green },
        CocExplorerGitModified = { fg = palette.dark.yellow },
        CocExplorerGitContentChange = { fg = palette.dark.yellow },
        CocExplorerGitPathChange = { fg = palette.dark.magenta },
        CocExplorerGitIgnored = { fg = palette.brights.black },
        CocExplorerGitUntracked = { fg = palette.brights.black },
        DapUIScope = { fg = palette.dark.cyan },
        DapUIType = { fg = palette.dark.magenta },
        DapUIModifiedValue = { bold = true, fg = palette.dark.cyan },
        DapUIDecoration = { link = "DapUIScope" },
        DapUIThread = { bold = true, fg = palette.brights.green },
        DapUIStoppedThread = { link = "DapUIScope" },
        DapUISource = { link = "DapUIType" },
        DapUILineNumber = { link = "DapUIScope" },
        DapUIFloatBorder = { link = "DapUIScope" },
        DapUIWatchesEmpty = { fg = palette.brights.red },
        DapUIWatchesValue = { fg = palette.brights.green },
        DapUIWatchesError = { link = "DapUIWatchesEmpty" },
        DapUIBreakpointsPath = { link = "DapUIScope" },
        DapUIBreakpointsInfo = { link = "DapUIWatchesValue" },
        DapUIBreakpointsCurrentLine = { link = "DapUIThread" },
        DapUIBreakpointsDisabledLine = { fg = palette.extra.gray1 },
        DapUIStepOver = { link = "DapUIScope" },
        DapUIStepInto = { link = "DapUIScope" },
        DapUIStepBack = { link = "DapUIScope" },
        DapUIStepOut = { link = "DapUIScope" },
        DapUIStop = { link = "DapUIWatchesEmpty" },
        DapUIPlayPause = { link = "DapUIWatchesValue" },
        DapUIRestart = { link = "DapUIWatchesValue" },
        DapUIUnavailable = { link = "DapUIBreakpointsDisabledLine" },
        DapUIWinSelect = { link = "DapUIModifiedValue" },
        DashboardShortCut = { link = "Identifier" },
        DashboardHeader = { link = "Title" },
        DashboardCenter = { link = "String" },
        DashboardFooter = { italic = true, fg = palette.normal },
        WhichKeyFloat = { bg = none },
        WhichKeyDesc = { link = "Keyword" },
        WhichKey = { link = "Identifier" },
        cssBraces = { fg = palette.normal },
        CmpDocumentation = { fg = palette.brights.white, bg = palette.extra.gray1 },
        SignColumnSB = { link = "SignColumn" },
        diffLine = { fg = palette.brights.white },
        FidgetTask = { link = "LineNr" },
        IndentBlanklineContextStart = { underline = true, sp = palette.dark.yellow },
        IndentBlanklineContextChar = { fg = palette.light.cyan },
        IndentBlanklineChar = { fg = palette.extra.gray1 },
        Italic = { italic = true },
        qfLineNr = { link = "LineNr" },
        qfFileName = { link = "Directory" },
        xmlAttrib = { link = "htmlTag" },
        diffNewFile = { fg = palette.extra.gray4 },
        diffFile = { fg = palette.ansi.cyan },
        CmpDocumentationBorder = { fg = palette.light.blue, bg = none },
        BlinkCmpMenu = { bg = palette.extra.gray1 },
        BlinkCmpKindText = { fg = palette.normal },
        BlinkCmpLabelMatch = { fg = palette.normal, bg = palette.light.yellow },
        BlinkCmpSignatureHelp = { fg = palette.ansi.magenta, bg = palette.extra.gray1 },
        BlinkCmpSignatureHelpBorder = { fg = palette.ansi.cyan, bg = palette.extra.gray1 },
        BlinkCmpSignatureHelpActiveParameter = { fg = palette.ansi.red, bg = palette.extra.gray1 },
        GitGutterAddLineNr = {},
        GitGutterChangeLineNr = {},
        GitGutterDeleteLineNr = {},
        GitGutterAddLine = {},
        SignifyLineAdd = {},
        GitGutterChangeLine = {},
        SignifyLineChange = {},
        GitGutterDeleteLine = {},
        SignifyLineDelete = {},
        DiffNoEOL = {},
        CodeCompanionChatInfo = { link = "DiagnosticInfo" },
        CodeCompanionChatError = { link = "DiagnosticError" },
        CodeCompanionChatWarn = { link = "DiagnosticWarn" },
        CodeCompanionChatSubtext = { link = "Comment" },
        CodeCompanionChatFold = { link = "@markup.quote.markdown" },
        CodeCompanionChatHeader = { link = "@markup.heading.2.markdown" },
        CodeCompanionChatSeparator = { link = "@punctuation.special.markdown" },
        CodeCompanionChatTokens = { link = "Comment" },
        CodeCompanionChatTool = { link = "Special" },
        CodeCompanionChatToolFailure = { link = "DiagnosticError" },
        CodeCompanionChatToolFailureIcon = { link = "Error" },
        CodeCompanionChatToolGroup = { link = "Constant" },
        CodeCompanionChatToolInProgress = { link = "DiagnosticInfo" },
        CodeCompanionChatToolInProgressIcon = { link = "DiagnosticInfo" },
        CodeCompanionChatToolPending = { link = "DiagnosticWarn" },
        CodeCompanionChatToolPendingIcon = { link = "DiagnosticWarn" },
        CodeCompanionChatToolSuccess = { link = "DiagnosticOk" },
        CodeCompanionChatToolSuccessIcon = { link = "DiagnosticOk" },
        CodeCompanionChatVariable = { link = "Identifier" },
        CodeCompanionChatInfoBanner = { link = "WildMenu" },
        CodeCompanionVirtualText = { link = "Comment" },
        CodeCompanionInlineDiffHint = { bg = palette.extra.gray1 },
        CopilotAnnotation = { link = "Comment" },
        CopilotSuggestion = { link = "Comment" },
        HoverFloatingError = { link = "DiagnosticFloatingError" },
        HoverFloatingWarn = { link = "DiagnosticFloatingWarn" },
        HoverFloatingInfo = { link = "DiagnosticFloatingInfo" },
        HoverFloatingHint = { link = "DiagnosticFloatingHint" },
        HoverWindow = { link = "NormalFloat" },
        HoverBorder = { link = "FloatBorder" },
        HoverSourceLine = { link = "TabLine" },
        HoverActiveSource = { link = "TabLineSel" },
        HoverInactiveSource = { link = "TabLineFill" },
    },

    lualine = {
        lualine_transparent = { fg = palette.normal, bg = none },
        lualine_b_command = { fg = palette.normal, bg = none },
        lualine_a_command = { fg = palette.normal, bg = none },
        lualine_a_replace = { fg = palette.normal, bg = palette.light.red },
        lualine_c_command = { fg = palette.normal, bg = none },
        lualine_b_terminal = { fg = palette.normal, bg = none },
        lualine_a_terminal = { fg = palette.normal, bg = none },
        lualine_c_terminal = { fg = palette.normal, bg = none },
        lualine_b_normal = { fg = palette.normal, bg = none },
        lualine_a_normal = { fg = palette.normal, bg = none },
        lualine_c_normal = { fg = palette.normal, bg = none },
        lualine_b_visual = { fg = palette.normal, bg = palette.light.blue },
        lualine_a_visual = { fg = palette.normal, bg = palette.light.blue },
        lualine_c_visual = { fg = palette.normal, bg = palette.light.blue },
        lualine_b_replace = { fg = palette.normal, bg = palette.light.red },
        lualine_c_replace = { fg = palette.normal, bg = palette.light.red },
        lualine_b_insert = { fg = palette.normal, bg = palette.light.green },
        lualine_a_insert = { fg = palette.normal, bg = palette.light.green },
        lualine_c_insert = { fg = palette.normal, bg = palette.light.green },
        lualine_b_inactive = { fg = palette.normal, bg = none },
        lualine_a_inactive = { fg = palette.normal, bg = none },
        lualine_c_inactive = { fg = palette.normal, bg = none },
        lualine_b_diff_added_normal = { fg = palette.ansi.green, bg = none },
        lualine_b_diff_added_insert = { fg = palette.ansi.green, bg = palette.light.green },
        lualine_b_diff_added_visual = { fg = palette.ansi.green, bg = palette.light.blue },
        lualine_b_diff_added_replace = { fg = palette.ansi.green, bg = palette.light.red },
        lualine_b_diff_added_command = { fg = palette.ansi.green, bg = none },
        lualine_b_diff_added_terminal = { fg = palette.ansi.green, bg = none },
        lualine_b_diff_added_inactive = { fg = palette.ansi.green, bg = none },
        lualine_b_diff_modified_normal = { fg = palette.brights.yellow, bg = none },
        lualine_b_diff_modified_insert = { fg = palette.brights.yellow, bg = palette.light.green },
        lualine_b_diff_modified_visual = { fg = palette.brights.yellow, bg = palette.light.blue },
        lualine_b_diff_modified_replace = { fg = palette.brights.yellow, bg = palette.light.red },
        lualine_b_diff_modified_command = { fg = palette.brights.yellow, bg = none },
        lualine_b_diff_modified_terminal = { fg = palette.brights.yellow, bg = none },
        lualine_b_diff_modified_inactive = { fg = palette.brights.yellow, bg = none },
        lualine_b_diff_removed_normal = { fg = palette.ansi.red, bg = none },
        lualine_b_diff_removed_insert = { fg = palette.ansi.red, bg = palette.light.green },
        lualine_b_diff_removed_visual = { fg = palette.ansi.red, bg = palette.light.blue },
        lualine_b_diff_removed_replace = { fg = palette.ansi.red, bg = palette.light.red },
        lualine_b_diff_removed_command = { fg = palette.ansi.red, bg = none },
        lualine_b_diff_removed_terminal = { fg = palette.ansi.red, bg = none },
        lualine_b_diff_removed_inactive = { fg = palette.ansi.red, bg = none },
        lualine_x_diagnostics_error_normal = { fg = palette.ansi.red, bg = none },
        lualine_x_diagnostics_error_insert = { fg = palette.ansi.red, bg = palette.light.green },
        lualine_x_diagnostics_error_visual = { fg = palette.ansi.red, bg = palette.light.blue },
        lualine_x_diagnostics_error_replace = { fg = palette.ansi.red, bg = palette.light.red },
        lualine_x_diagnostics_error_command = { fg = palette.ansi.red, bg = none },
        lualine_x_diagnostics_error_terminal = { fg = palette.ansi.red, bg = none },
        lualine_x_diagnostics_error_inactive = { fg = palette.ansi.red, bg = none },
        lualine_x_diagnostics_warn_normal = { fg = palette.ansi.yellow, bg = none },
        lualine_x_diagnostics_warn_insert = { fg = palette.ansi.yellow, bg = palette.light.green },
        lualine_x_diagnostics_warn_visual = { fg = palette.ansi.yellow, bg = palette.light.blue },
        lualine_x_diagnostics_warn_replace = { fg = palette.ansi.yellow, bg = palette.light.red },
        lualine_x_diagnostics_warn_command = { fg = palette.ansi.yellow, bg = none },
        lualine_x_diagnostics_warn_terminal = { fg = palette.ansi.yellow, bg = none },
        lualine_x_diagnostics_warn_inactive = { fg = palette.ansi.yellow, bg = none },
        lualine_x_diagnostics_info_normal = { fg = palette.ansi.blue, bg = none },
        lualine_x_diagnostics_info_insert = { fg = palette.ansi.blue, bg = palette.light.green },
        lualine_x_diagnostics_info_visual = { fg = palette.ansi.blue, bg = palette.light.blue },
        lualine_x_diagnostics_info_replace = { fg = palette.ansi.blue, bg = palette.light.red },
        lualine_x_diagnostics_info_command = { fg = palette.ansi.blue, bg = none },
        lualine_x_diagnostics_info_terminal = { fg = palette.ansi.blue, bg = none },
        lualine_x_diagnostics_info_inactive = { fg = palette.ansi.blue, bg = none },
        lualine_x_diagnostics_hint_normal = { fg = palette.ansi.cyan, bg = none },
        lualine_x_diagnostics_hint_insert = { fg = palette.ansi.cyan, bg = palette.light.green },
        lualine_x_diagnostics_hint_visual = { fg = palette.ansi.cyan, bg = palette.light.blue },
        lualine_x_diagnostics_hint_replace = { fg = palette.ansi.cyan, bg = palette.light.red },
        lualine_x_diagnostics_hint_command = { fg = palette.ansi.cyan, bg = none },
        lualine_x_diagnostics_hint_terminal = { fg = palette.ansi.cyan, bg = none },
        lualine_x_diagnostics_hint_inactive = { fg = palette.ansi.cyan, bg = none },
    },

    default = {

        Identifier = { fg = palette.normal },
        SpecialKey = { link = "NonText" },
        EndOfBuffer = { fg = palette.normal },
        TermCursor = { reverse = true },
        Cursor = { fg = palette.normal, bg = palette.cursor },
        CursorLineNr = { bg = palette.extra.gray0 },
        CursorLineSign = { bg = palette.extra.gray0 },
        CursorLineFold = { link = "FoldColumn" },
        CursorColumn = { link = "CursorLine" },
        CursorLine = { bg = palette.extra.gray0 },
        lCursor = { link = "Cursor" },
        CursorIM = { link = "Cursor" },
        NonText = { fg = palette.extra.gray2 },
        Directory = { fg = palette.brights.white },
        ErrorMsg = { fg = palette.ansi.red },
        IncSearch = { fg = palette.normal, bg = palette.dark.yellow },
        Search = { bg = palette.light.yellow },
        CurSearch = { link = "IncSearch" },
        MoreMsg = { bold = true, fg = palette.ansi.blue },
        ModeMsg = { bold = true, fg = palette.ansi.yellow },
        LineNr = { fg = palette.brights.black },
        LineNrAbove = { link = "LineNr" },
        LineNrBelow = { link = "LineNr" },
        Question = { link = "MoreMsg" },
        StatusLine = { fg = palette.normal, bg = none },
        StatusLineNC = { underline = true, fg = palette.extra.bg1, bg = palette.extra.bg1, sp = palette.extra.bg1 },
        WinSeparator = { fg = palette.extra.pencilGray },
        VertSplit = { fg = palette.extra.pencilGray },
        Title = { bold = true, fg = palette.brights.white },
        Visual = { bg = palette.extra.gray1 },
        VisualNC = {},
        WarningMsg = { fg = palette.ansi.yellow },
        WildMenu = { link = "Pmenu" },
        Folded = { fg = palette.brights.black, bg = palette.extra.bg1 },
        FoldColumn = { fg = palette.brights.black },
        DiffAdd = { link = "diffAdded" },
        DiffChange = { link = "diffChanged" },
        DiffDelete = { link = "diffRemoved" },
        DiffText = { fg = palette.normal, bg = palette.dark.yellow },
        SignColumn = { fg = palette.brights.black },
        Conceal = { fg = palette.brights.black },
        SpellBad = { undercurl = true, sp = palette.ansi.red },
        SpellCap = { undercurl = true, sp = palette.ansi.yellow },
        SpellRare = { undercurl = true, sp = palette.ansi.blue },
        SpellLocal = { undercurl = true, sp = palette.ansi.blue },
        Pmenu = { fg = palette.normal, bg = palette.extra.gray1 },
        PmenuSel = { fg = none, bg = palette.extra.gray5 },
        PmenuMatch = { bold = true },
        PmenuMatchSel = { bold = true },
        PmenuKind = { link = "Pmenu" },
        PmenuKindSel = { link = "PmenuSel" },
        PmenuExtra = { link = "Pmenu" },
        PmenuExtraSel = { link = "PmenuSel" },
        PmenuSbar = { link = "Pmenu" },
        PmenuThumb = { bg = none },
        TabLine = { fg = palette.normal, bg = palette.extra.gray4 },
        TabLineSel = { fg = none, bg = palette.brights.black },
        TabLineFill = {},
        ColorColumn = { bg = palette.extra.bg1 },
        QuickFixLine = { link = "CursorLine" },
        Whitespace = { fg = palette.extra.gray4 },
        NormalNC = { fg = palette.normal },
        MsgSeparator = { link = "StatusLine" },
        NormalFloat = {},
        MsgArea = {},
        FloatBorder = { fg = palette.extra.gray2 },
        WinBar = { bold = true, fg = palette.brights.black },
        WinBarNC = { bold = true, fg = palette.brights.black },
        FloatTitle = {},
        FloatFooter = { link = "FloatTitle" },
        StatusLineTerm = { link = "StatusLine" },
        StatusLineTermNC = { link = "StatusLineNC" },
        RedrawDebugNormal = { reverse = true },
        Underlined = { underline = true },
        ComplMatchIns = {},
        Substitute = { fg = palette.ansi.black, bg = palette.ansi.red },
        VisualNOS = { link = "Visual" },
        Normal = { fg = palette.normal },
        Character = { link = "String" },
        Constant = { bold = true, fg = palette.normal },
        Number = { fg = palette.normal },
        Boolean = { link = "Number" },
        Float = { link = "Number" },
        Conditional = { fg = palette.normal },
        Statement = { bold = true, fg = palette.normal },
        Repeat = { link = "Conditional" },
        Label = { link = "Conditional" },
        Keyword = { bold = true, fg = palette.normal },
        Exception = { link = "Keyword" },
        Include = { link = "PreProc" },
        PreProc = { fg = palette.normal },
        Define = { link = "PreProc" },
        Macro = { link = "PreProc" },
        PreCondit = { link = "PreProc" },
        StorageClass = { link = "Type" },
        Type = { italic = true, fg = palette.brights.white },
        Structure = { link = "Type" },
        Typedef = { link = "Type" },
        Tag = { fg = palette.ansi.blue },
        ["@tag"] = { fg = palette.ansi.blue },
        Special = { fg = palette.normal, bold = true },
        SpecialChar = { link = "Special" },
        SpecialComment = { link = "Special" },
        Debug = { link = "Special" },
        Ignore = { link = "Normal" },
        LspCodeLens = { fg = palette.brights.black },
        LspCodeLensSeparator = { fg = palette.brights.black },
        LspInlayHint = { fg = palette.brights.black, bg = palette.extra.gray2 },
        LspReferenceRead = { bg = palette.light.blue },
        LspReferenceText = { bg = palette.light.blue },
        LspReferenceWrite = { bg = palette.light.blue },
        LspReferenceTarget = { link = "LspReferenceText" },
        LspSignatureActiveParameter = { fg = palette.dark.cyan },
        SnippetTabstop = { link = "Visual" },
        DiagnosticFloatingError = { link = "DiagnosticError" },
        DiagnosticError = { fg = palette.brights.red },
        DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
        DiagnosticWarn = { fg = palette.brights.yellow },
        DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
        DiagnosticInfo = { fg = palette.ansi.cyan },
        DiagnosticFloatingHint = { link = "DiagnosticHint" },
        DiagnosticHint = { fg = palette.ansi.cyan },
        DiagnosticFloatingOk = { link = "DiagnosticOk" },
        DiagnosticOk = { fg = "NvimDarkGreen" },
        DiagnosticVirtualTextError = { fg = palette.brights.red },
        DiagnosticVirtualTextWarn = { fg = palette.dark.yellow },
        DiagnosticVirtualTextInfo = { fg = palette.ansi.cyan },
        DiagnosticVirtualTextHint = { fg = palette.light.cyan },
        DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
        DiagnosticVirtualLinesError = { link = "DiagnosticError" },
        DiagnosticVirtualLinesWarn = { link = "DiagnosticWarn" },
        DiagnosticVirtualLinesInfo = { link = "DiagnosticInfo" },
        DiagnosticVirtualLinesHint = { link = "DiagnosticHint" },
        DiagnosticVirtualLinesOk = { link = "DiagnosticOk" },
        DiagnosticSignError = { link = "DiagnosticError" },
        DiagnosticSignWarn = { link = "DiagnosticWarn" },
        DiagnosticSignInfo = { link = "DiagnosticInfo" },
        DiagnosticSignHint = { link = "DiagnosticHint" },
        DiagnosticSignOk = { link = "DiagnosticOk" },
        DiagnosticUnnecessary = { link = "Comment" },
        Comment = { italic = true, nocombine = true, fg = palette.brights.black, bg = none },
        String = { fg = palette.brights.green },
        Function = { fg = palette.ansi.cyan },
        Operator = { fg = palette.normal },
        Delimiter = { link = "Special" },
        Todo = { fg = palette.normal, bg = palette.ansi.cyan },
        Added = { fg = palette.brights.green, bg = palette.light.green },
        Removed = { fg = palette.brights.red, bg = palette.light.cyan },
        Changed = { fg = palette.brights.yellow, bg = palette.light.yellow },
        DiagnosticDeprecated = { strikethrough = true, sp = "NvimDarkRed" },
        MatchParen = { bold = true, fg = palette.brights.white, bg = palette.light.blue },
        Error = { fg = palette.brights.red },
        DiagnosticUnderlineError = { undercurl = true, sp = palette.brights.red },
        DiagnosticUnderlineWarn = { undercurl = true, sp = palette.dark.yellow },
        DiagnosticUnderlineInfo = { undercurl = true, sp = palette.ansi.cyan },
        DiagnosticUnderlineHint = { undercurl = true, sp = palette.light.cyan },
        DiagnosticUnderlineOk = { underline = true, sp = "NvimDarkGreen" },
        NvimInternalError = { fg = "Red", bg = "Red" },
        NvimAssignment = { link = "Operator" },
        NvimPlainAssignment = { link = "NvimAssignment" },
        NvimAugmentedAssignment = { link = "NvimAssignment" },
        NvimAssignmentWithAddition = { link = "NvimAugmentedAssignment" },
        NvimAssignmentWithSubtraction = { link = "NvimAugmentedAssignment" },
        NvimAssignmentWithConcatenation = { link = "NvimAugmentedAssignment" },
        NvimOperator = { link = "Operator" },
        NvimUnaryOperator = { link = "NvimOperator" },
        NvimUnaryPlus = { link = "NvimUnaryOperator" },
        NvimUnaryMinus = { link = "NvimUnaryOperator" },
        NvimNot = { link = "NvimUnaryOperator" },
        NvimBinaryOperator = { link = "NvimOperator" },
        NvimComparison = { link = "NvimBinaryOperator" },
        NvimComparisonModifier = { link = "NvimComparison" },
        NvimBinaryPlus = { link = "NvimBinaryOperator" },
        NvimBinaryMinus = { link = "NvimBinaryOperator" },
        NvimConcat = { link = "NvimBinaryOperator" },
        NvimConcatOrSubscript = { link = "NvimConcat" },
        NvimOr = { link = "NvimBinaryOperator" },
        NvimAnd = { link = "NvimBinaryOperator" },
        NvimMultiplication = { link = "NvimBinaryOperator" },
        NvimDivision = { link = "NvimBinaryOperator" },
        NvimMod = { link = "NvimBinaryOperator" },
        NvimTernary = { link = "NvimOperator" },
        NvimTernaryColon = { link = "NvimTernary" },
        NvimParenthesis = { link = "Delimiter" },
        NvimLambda = { link = "NvimParenthesis" },
        NvimNestingParenthesis = { link = "NvimParenthesis" },
        NvimCallingParenthesis = { link = "NvimParenthesis" },
        NvimSubscript = { link = "NvimParenthesis" },
        NvimSubscriptBracket = { link = "NvimSubscript" },
        NvimSubscriptColon = { link = "NvimSubscript" },
        NvimCurly = { link = "NvimSubscript" },
        NvimContainer = { link = "NvimParenthesis" },
        NvimDict = { link = "NvimContainer" },
        NvimList = { link = "NvimContainer" },
        NvimIdentifier = { link = "Identifier" },
        NvimIdentifierScope = { link = "NvimIdentifier" },
        NvimIdentifierScopeDelimiter = { link = "NvimIdentifier" },
        NvimIdentifierName = { link = "NvimIdentifier" },
        NvimIdentifierKey = { link = "NvimIdentifier" },
        NvimColon = { link = "Delimiter" },
        NvimComma = { link = "Delimiter" },
        NvimArrow = { link = "Delimiter" },
        NvimRegister = { link = "SpecialChar" },
        NvimNumber = { link = "Number" },
        NvimFloat = { link = "NvimNumber" },
        NvimNumberPrefix = { link = "Type" },
        NvimOptionSigil = { link = "Type" },
        NvimOptionName = { link = "NvimIdentifier" },
        NvimOptionScope = { link = "NvimIdentifierScope" },
        NvimOptionScopeDelimiter = { link = "NvimIdentifierScopeDelimiter" },
        NvimEnvironmentSigil = { link = "NvimOptionSigil" },
        NvimEnvironmentName = { link = "NvimIdentifier" },
        NvimString = { link = "String" },
        NvimStringBody = { link = "NvimString" },
        NvimStringQuote = { link = "NvimString" },
        NvimStringSpecial = { link = "SpecialChar" },
        NvimSingleQuote = { link = "NvimStringQuote" },
        NvimSingleQuotedBody = { link = "NvimStringBody" },
        NvimSingleQuotedQuote = { link = "NvimStringSpecial" },
        NvimDoubleQuote = { link = "NvimStringQuote" },
        NvimDoubleQuotedBody = { link = "NvimStringBody" },
        NvimDoubleQuotedEscape = { link = "NvimStringSpecial" },
        NvimFigureBrace = { link = "NvimInternalError" },
        NvimSingleQuotedUnknownEscape = { link = "NvimInternalError" },
        NvimSpacing = { link = "Normal" },
        NvimInvalidSingleQuotedUnknownEscape = { link = "NvimInternalError" },
        NvimInvalid = { link = "Error" },
        NvimInvalidAssignment = { link = "NvimInvalid" },
        NvimInvalidPlainAssignment = { link = "NvimInvalidAssignment" },
        NvimInvalidAugmentedAssignment = { link = "NvimInvalidAssignment" },
        NvimInvalidAssignmentWithAddition = { link = "NvimInvalidAugmentedAssignment" },
        NvimInvalidAssignmentWithSubtraction = { link = "NvimInvalidAugmentedAssignment" },
        NvimInvalidAssignmentWithConcatenation = { link = "NvimInvalidAugmentedAssignment" },
        NvimInvalidOperator = { link = "NvimInvalid" },
        NvimInvalidUnaryOperator = { link = "NvimInvalidOperator" },
        NvimInvalidUnaryPlus = { link = "NvimInvalidUnaryOperator" },
        NvimInvalidUnaryMinus = { link = "NvimInvalidUnaryOperator" },
        NvimInvalidNot = { link = "NvimInvalidUnaryOperator" },
        NvimInvalidBinaryOperator = { link = "NvimInvalidOperator" },
        NvimInvalidComparison = { link = "NvimBinaryOperator" },
        NvimInvalidComparisonModifier = { link = "NvimComparison" },
        NvimInvalidBinaryPlus = { link = "NvimBinaryOperator" },
        NvimInvalidBinaryMinus = { link = "NvimBinaryOperator" },
        NvimInvalidConcat = { link = "NvimBinaryOperator" },
        NvimInvalidConcatOrSubscript = { link = "NvimInvalidConcat" },
        NvimInvalidOr = { link = "NvimBinaryOperator" },
        NvimInvalidAnd = { link = "NvimBinaryOperator" },
        NvimInvalidMultiplication = { link = "NvimBinaryOperator" },
        NvimInvalidDivision = { link = "NvimBinaryOperator" },
        NvimInvalidMod = { link = "NvimBinaryOperator" },
        NvimInvalidTernary = { link = "NvimOperator" },
        NvimInvalidTernaryColon = { link = "NvimInvalidTernary" },
        NvimInvalidDelimiter = { link = "NvimInvalid" },
        NvimInvalidParenthesis = { link = "NvimInvalidDelimiter" },
        NvimInvalidLambda = { link = "NvimInvalidParenthesis" },
        NvimInvalidNestingParenthesis = { link = "NvimInvalidParenthesis" },
        NvimInvalidCallingParenthesis = { link = "NvimInvalidParenthesis" },
        NvimInvalidSubscript = { link = "NvimInvalidParenthesis" },
        NvimInvalidSubscriptBracket = { link = "NvimInvalidSubscript" },
        NvimInvalidSubscriptColon = { link = "NvimInvalidSubscript" },
        NvimInvalidCurly = { link = "NvimInvalidSubscript" },
        NvimInvalidContainer = { link = "NvimInvalidParenthesis" },
        NvimInvalidDict = { link = "NvimInvalidContainer" },
        NvimInvalidList = { link = "NvimInvalidContainer" },
        NvimInvalidValue = { link = "NvimInvalid" },
        NvimInvalidIdentifier = { link = "NvimInvalidValue" },
        NvimInvalidIdentifierScope = { link = "NvimInvalidIdentifier" },
        NvimInvalidIdentifierScopeDelimiter = { link = "NvimInvalidIdentifier" },
        NvimInvalidIdentifierName = { link = "NvimInvalidIdentifier" },
        NvimInvalidIdentifierKey = { link = "NvimInvalidIdentifier" },
        NvimInvalidColon = { link = "NvimInvalidDelimiter" },
        NvimInvalidComma = { link = "NvimInvalidDelimiter" },
        NvimInvalidArrow = { link = "NvimInvalidDelimiter" },
        NvimInvalidRegister = { link = "NvimInvalidValue" },
        NvimInvalidNumber = { link = "NvimInvalidValue" },
        NvimInvalidFloat = { link = "NvimInvalidNumber" },
        NvimInvalidNumberPrefix = { link = "NvimInvalidNumber" },
        NvimInvalidOptionSigil = { link = "NvimInvalidIdentifier" },
        NvimInvalidOptionName = { link = "NvimInvalidIdentifier" },
        NvimInvalidOptionScope = { link = "NvimInvalidIdentifierScope" },
        NvimInvalidOptionScopeDelimiter = { link = "NvimInvalidIdentifierScopeDelimiter" },
        NvimInvalidEnvironmentSigil = { link = "NvimInvalidOptionSigil" },
        NvimInvalidEnvironmentName = { link = "NvimInvalidIdentifier" },
        NvimInvalidString = { link = "NvimInvalidValue" },
        NvimInvalidStringBody = { link = "NvimStringBody" },
        NvimInvalidStringQuote = { link = "NvimInvalidString" },
        NvimInvalidStringSpecial = { link = "NvimStringSpecial" },
        NvimInvalidSingleQuote = { link = "NvimInvalidStringQuote" },
        NvimInvalidSingleQuotedBody = { link = "NvimInvalidStringBody" },
        NvimInvalidSingleQuotedQuote = { link = "NvimInvalidStringSpecial" },
        NvimInvalidDoubleQuote = { link = "NvimInvalidStringQuote" },
        NvimInvalidDoubleQuotedBody = { link = "NvimInvalidStringBody" },
        NvimInvalidDoubleQuotedEscape = { link = "NvimInvalidStringSpecial" },
        NvimInvalidDoubleQuotedUnknownEscape = { link = "NvimInvalidValue" },
        NvimInvalidFigureBrace = { link = "NvimInvalidDelimiter" },
        NvimInvalidSpacing = { link = "ErrorMsg" },
        NvimDoubleQuotedUnknownEscape = { link = "NvimInvalidValue" },
    },

    mini = {

        MiniCompletionActiveParameter = { underline = true },

        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { link = "NormalFloat" },

        MiniHipatternsFixme = { fg = palette.normal, bg = palette.light.red },
        MiniHipatternsHack = { fg = palette.normal, bg = palette.light.yellow },
        MiniHipatternsTodo = { fg = palette.normal, bg = palette.light.green },
        MiniHipatternsNote = { fg = palette.normal, bg = palette.light.blue },

        MiniJump2dDim = { link = "Comment" },
        MiniJump2dSpot = { bold = true, fg = palette.ansi.black, bg = palette.ansi.green },
        MiniJump2dSpotUnique = { bold = true, fg = palette.ansi.black, bg = palette.ansi.cyan },
        MiniJump = { link = "SpellRare" },
        MiniJump2dSpotAhead = { nocombine = true, fg = palette.ansi.cyan },

        MiniDiffSignAdd = { fg = palette.brights.green },
        MiniDiffSignDelete = { fg = palette.ansi.red },
        MiniDiffSignChange = { fg = palette.ansi.yellow },
        MiniDiffOverContext = { link = "DiffChange" },
        MiniDiffOverChange = { fg = palette.ansi.black, bg = palette.ansi.yellow },
        MiniDiffOverDelete = { link = "DiffDelete" },
        MiniDiffOverAdd = { link = "DiffAdd" },

        MiniCursorwordCurrent = { bg = palette.extra.gray4 },
        MiniCursorword = { bg = palette.extra.gray0 },

        MiniFilesCursorLine = { link = "CursorLine" },
        MiniFilesNormal = { fg = palette.normal },
        MiniFilesTitle = { link = "FloatTitle" },
        MiniFilesTitleFocused = { bold = true, fg = palette.brights.white },
        MiniFilesBorder = { link = "FloatBorder" },
        MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
        MiniFilesDirectory = { link = "Directory" },
        MiniFilesFile = { fg = palette.normal },

        MiniDepsChangeAdded = { link = "diffAdded" },
        MiniDepsChangeRemoved = { link = "diffRemoved" },
        MiniDepsHint = { link = "DiagnosticHint" },
        MiniDepsInfo = { link = "DiagnosticInfo" },
        MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
        MiniDepsPlaceholder = { link = "Comment" },
        MiniDepsTitle = { link = "Title" },
        MiniDepsTitleError = { link = "DiffDelete" },
        MiniDepsTitleSame = { link = "DiffText" },
        MiniDepsTitleUpdate = { link = "DiffAdd" },

        MiniIconsAzure = { fg = palette.ansi.blue },
        MiniIconsBlue = { fg = palette.ansi.blue },
        MiniIconsCyan = { fg = palette.ansi.cyan },
        MiniIconsGreen = { fg = palette.ansi.green },
        MiniIconsGrey = { fg = palette.brights.black },
        MiniIconsOrange = { fg = palette.brights.yellow },
        MiniIconsPurple = { fg = palette.ansi.magenta },
        MiniIconsRed = { fg = palette.ansi.red },
        MiniIconsYellow = { fg = palette.ansi.yellow },

        MiniNotifyBorder = { fg = palette.extra.gray1 },
        MiniNotifyNormal = { link = "NormalFloat" },
        MiniNotifyLspProgress = { link = "MiniNotifyNormal" },
        MiniNotifyTitle = { fg = palette.extra.bg2 },

        MiniPickHeader = { fg = palette.brights.white },
        MiniPickPreviewLine = { link = "CursorLine" },
        MiniPickPreviewRegion = { link = "IncSearch" },
        MiniPickMatchRanges = { fg = palette.normal, bg = palette.light.yellow },
        MiniPickPromptCaret = { fg = palette.extra.gray2 },
        MiniPickPromptPrefix = { fg = palette.extra.gray2 },
        MiniPickPrompt = { fg = palette.normal },
        MiniPickBorder = { link = "FloatBorder" },
        MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
        MiniPickBorderText = { link = "FloatTitle" },
        MiniPickIconDirectory = { link = "Directory" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniPickIconFile = { link = "MiniPickNormal" },
        MiniPickMatchCurrent = { link = "CursorLine" },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickCursor = { nocombine = true, blend = 100 },

        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { italic = true, fg = palette.extra.gray2 },
        MiniStarterHeader = { fg = palette.ansi.cyan },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { fg = palette.brights.white },
        MiniStarterItemPrefix = { fg = palette.brights.yellow },
        MiniStarterSection = { link = "Special" },
        MiniStarterQuery = { fg = palette.ansi.cyan },

        MiniStatuslineDevinfo = { fg = palette.brights.white, bg = palette.light.cyan },
        MiniStatuslineFileinfo = { fg = palette.brights.white, bg = palette.light.cyan },
        MiniStatuslineFilename = { fg = palette.extra.gray3, bg = none },
        MiniStatuslineInactive = { fg = palette.extra.gray3, bg = none },
        MiniStatuslineModeCommand = { bold = true, fg = none, bg = palette.light.magenta },
        MiniStatuslineModeInsert = { bold = true, fg = palette.normal, bg = palette.light.green },
        MiniStatuslineModeNormal = { bold = true, fg = palette.normal, bg = palette.ansi.cyan },
        MiniStatuslineModeOther = { bold = true, fg = palette.normal },
        MiniStatuslineModeReplace = { bold = true, fg = palette.normal, bg = palette.light.red },
        MiniStatuslineModeVisual = { bold = true, fg = palette.normal, bg = palette.light.yellow },

        MiniSurround = { link = "IncSearch" },

        MiniTablineCurrent = { bold = true, fg = none, bg = palette.dark.blue },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = palette.brights.white, bg = none },
        MiniTablineModifiedCurrent = { bold = true, fg = palette.ansi.blue, bg = none },
        MiniTablineModifiedHidden = { fg = palette.normal, bg = palette.brights.white },
        MiniTablineModifiedVisible = { fg = palette.cyan, bg = none },
        MiniTablineTabpagesection = { bold = true, bg = palette.light.blue },
        MiniTablineVisible = { fg = palette.normal, bg = palette.light.blue },

        MiniTestEmphasis = { bold = true },
        MiniTestFail = { bold = true, fg = palette.ansi.red },
        MiniTestPass = { bold = true, fg = palette.ansi.green },
        MiniTrailspace = { bg = palette.light.red },

        MiniClueBorder = { link = "FloatBorder" },
        MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
        MiniClueDescSingle = { link = "NormalFloat" },
        MiniClueNextKey = { fg = palette.ansi.cyan },
        MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
        MiniClueSeparator = { fg = palette.extra.gray3 },
        MiniClueTitle = { link = "FloatTitle" },

        MiniMapNormal = { link = "NormalFloat" },
        MiniMapSymbolCount = { link = "Special" },
        MiniMapSymbolLine = { fg = palette.ansi.cyan },
        MiniMapSymbolView = { fg = palette.light.blue },

        MiniOperatorsExchangeFrom = { link = "IncSearch" },

        MiniIndentscopeSymbol = { link = "Delimiter" },
        MiniIndentscopePrefix = { nocombine = true },
    },

    neogit = {
        NeogitBranch = { fg = palette.dark.yellow },
        NeogitRemote = { fg = palette.extra.gray3 },
        NeogitHunkHeader = { fg = palette.ansi.cyan, bg = palette.light.blue },
        NeogitHunkHeaderHighlight = { fg = palette.ansi.cyan, bg = palette.light.blue },
        NeogitDiffAdd = { fg = palette.brights.green },
        NeogitDiffDelete = { fg = palette.brights.red },
        NeogitDiffAddHighlight = { bg = palette.light.green },
        NeogitDiffDeleteHighlight = { bg = palette.light.red },
        NeogitDiffContextHighlight = { bg = palette.extra.gray4 },
        NeogitNotificationInfo = { fg = palette.ansi.cyan },
        NeogitNotificationWarning = { fg = palette.dark.yellow },
        NeogitNotificationError = { fg = palette.brights.red },
        NormalSB = { fg = palette.brights.white },
        NeoTreeNormal = { link = "NormalSB" },
        NeoTreeNormalNC = { link = "NeoTreeNormal" },
        NeoTreeTitleBar = { fg = palette.normal, bg = palette.brights.blue },
        NeoTreeEndOfBuffer = { fg = palette.normal },
        NeoTreeIndentMarker = { fg = palette.extra.gray2 },
        NeoTreeRootName = { bold = true, fg = palette.brights.white },
        NeoTreeDirectoryName = { fg = palette.brights.white },
        NeoTreeDirectoryIcon = { fg = palette.brights.white },
        NeoTreeDotfile = { fg = palette.dark.blue },
        NeoTreeSymbolicLinkTarget = { fg = palette.dark.red },
        NeoTreeFileName = { fg = palette.brights.white },
        NeoTreeFileNameOpened = { fg = palette.ansi.blue },
        NeoTreeDimText = { link = "Conceal" },
        NeoTreeGitModified = { fg = palette.dark.yellow },
        NeoTreeGitAdded = { fg = palette.brights.green },
        NeoTreeGitDeleted = { fg = palette.brights.red },
        NeoTreeGitConflict = { italic = true, fg = palette.rainbow.orange },
        NeoTreeGitIgnored = { fg = palette.extra.gray1 },
        NeoTreeGitUntracked = { fg = palette.dark.cyan },
    },

    treesitter_context = {
        TreesitterContext = { bg = palette.extra.gray0 },
        TreesitterContextBottom = { underline = true, sp = palette.extra.gray1 },
        TreesitterContextLineNumber = { bg = palette.extra.gray0 },
        TreesitterContextLineNumberBottom = { underline = true, sp = palette.extra.gray1 },
        TreesitterContextSeparator = { link = "FloatBorder" },
    },

    lsp = {
        ["@lsp"] = {},
        ["@lsp.type.class"] = { fg = palette.ansi.magenta },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@attribute" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.event"] = { link = "@type" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@interface" },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.macro"] = { link = "@constant.macro" },
        ["@lsp.type.method"] = { link = "@function.method" },
        ["@lsp.type.modifier"] = { link = "@type.qualifier" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.number"] = { link = "@number" },
        ["@lsp.type.operator"] = { link = "@operator" },
        ["@lsp.type.parameter"] = { link = "@variable.parameter" },
        ["@lsp.type.property"] = {},
        ["@lsp.type.regexp"] = { link = "@string.regexp" },
        ["@lsp.type.string"] = { link = "@string" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = {},
        ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
        ["@lsp.type.method.yaml.ansible"] = { fg = palette.ansi.cyan },
        ["@lsp.type.keyword.yaml.ansible"] = { fg = palette.ansi.blue },
        ["@lsp.type.type.terraform"] = { fg = palette.brights.white },
        ["@lsp.mod.global.lua"] = { bold = true, fg = palette.brights.white },
        ["@lsp.typemod.function.defaultLibrary.lua"] = { fg = palette.ansi.magenta },
        ["@lsp.typemod.class.builtin.python"] = { italic = true, fg = palette.ansi.blue },
        ["@lsp.type.class.python"] = { fg = palette.ansi.blue },
        ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
        ["@lsp.type.variable.lua"] = {},
        ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
        ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
        ["@lsp.typemod.operator.injected"] = { link = "@operator" },
        ["@lsp.typemod.string.injected"] = { link = "@string" },
        ["@lsp.typemod.variable.injected"] = { link = "@variable" },
    },
    treesitter = {
        ["@module.builtin.lua"] = { fg = palette.ansi.magenta },
        ["@diff.delta"] = { link = "diffChanged" },
        ["@diff.minus"] = { link = "diffRemoved" },
        ["@constant.macro"] = { link = "Macro" },
        ["@type.qualifier"] = { fg = palette.normal },
        ["@markup"] = { link = "Special" },
        ["@markup.strong"] = { bold = true, fg = palette.brights.white },
        ["@markup.italic"] = { italic = true, fg = palette.brights.white },
        ["@markup.strikethrough"] = { strikethrough = true, fg = palette.brights.white },
        ["@markup.underline"] = { underline = true },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.link"] = { underline = true, fg = palette.brights.white },
        ["@diff"] = {},
        ["@diff.plus"] = { link = "diffAdded" },
        ["@keyword"] = { link = "Keyword" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Special" },
        ["@comment"] = { link = "Comment" },
        ["@comment.error"] = { fg = palette.extra.bg1, bg = palette.brights.red },
        ["@comment.warning"] = { fg = palette.extra.bg1, bg = palette.dark.yellow },
        ["@comment.note"] = { link = "DiagnosticInfo" },
        ["@comment.todo"] = { fg = palette.extra.bg1, bg = palette.extra.gray4 },
        ["@boolean.yaml"] = { bold = true },
        ["@boolean.terraform"] = { bold = true },
        ["@boolean.lua"] = { bold = true },
        ["@keyword.directive.jinja"] = { fg = palette.ansi.yellow },
        ["@keyword.conditional.ternary.c"] = { bold = true, fg = palette.ansi.yellow },
        ["@constant.builtin.c"] = { bold = true, fg = palette.brights.white },
        ["@boolean.python"] = { bold = true, fg = palette.brights.black },
        ["@namespace"] = {},
        ["@interface"] = {},
        ["@string.special.symbol"] = { link = "@constant" },
        ["@punctuation.bracket"] = { fg = palette.normal },
        ["@comment.hint"] = { fg = palette.extra.bg1, bg = palette.extra.gray4 },
        ["@comment.info"] = { fg = palette.extra.bg1, bg = palette.ansi.cyan },
        ["@markup.environment"] = { fg = palette.normal },
        ["@markup.environment.name"] = { fg = palette.ansi.cyan },
        ["@markup.link.uri"] = { underline = true, italic = true, fg = palette.normal },
        ["@markup.link.label"] = { link = "Special" },
        ["@markup.raw"] = { italic = true, fg = palette.normal },
        ["@markup.list"] = { fg = palette.brights.white },
        ["@markup.list.checked"] = { fg = palette.brights.green },
        ["@markup.list.unchecked"] = { fg = palette.brights.black },
        ["@variable.member"] = { fg = palette.normal },
        ["@tag.attribute"] = { link = "@variable.member" },
        ["@tag.delimiter"] = {},
        ["@none"] = { link = "NONE" },
        ["@conceal"] = { link = "Conceal" },
        ["@operator.bash"] = { fg = palette.normal },
        ["@function.builtin.bash"] = { fg = palette.normal },
        ["@function.call.bash"] = { fg = palette.normal },
        ["@number.bash"] = {},
        ["@punctuation.delimiter.bash"] = { fg = palette.normal },
        ["@markup.list.bash"] = { link = "@punctuation.bash" },
        ["@type.css"] = { link = "htmlTag" },
        ["@module.c_sharp"] = { fg = palette.brights.magenta },
        ["@string.special.path.gitignore"] = { fg = palette.brights.magenta },
        ["@module.go"] = {},
        ["@markup.heading.html"] = { fg = palette.brights.white },
        ["@constant.html"] = { link = "@tag" },
        ["@tag.javascript"] = { link = "@type.javascript" },
        ["@tag.tsx"] = { link = "@type.tsx" },
        ["@tag.delimiter.javascript"] = { link = "@tag.attribute.javascript" },
        ["@tag.delimiter.tsx"] = { link = "@tag.attribute.tsx" },
        ["@property.json"] = { link = "@tag" },
        ["@constructor.lua"] = { fg = palette.normal },
        ["@operator.lua"] = { fg = palette.normal },
        ["@property.lua"] = { fg = palette.normal },
        ["@function.builtin.lua"] = { fg = palette.ansi.magenta },
        ["@property.luadoc"] = { link = "@property.lua" },
        ["@variable.member.luadoc"] = { link = "@property.luadoc" },
        ["@operator.luadoc"] = { fg = palette.brights.white },
        ["@markup.list.luadoc"] = { fg = palette.brights.white },
        ["@string.special.symbol.make"] = { link = "@function" },
        ["@function.builtin.make"] = { link = "@constant" },
        ["@punctuation.delimiter.markdown"] = { fg = palette.brights.white },
        ["@punctuation.delimiter.markdown_inline"] = { fg = palette.brights.white },
        ["@markup.quote.markdown"] = { fg = palette.ansi.blue },
        ["@variable.member.nix"] = { link = "@variable.member" },
        ["@variable.parameter.nix"] = { link = "@variable.parameter" },
        ["@string.special.path.nix"] = { link = "@string" },
        ["@module.php"] = { link = "@constructor.php" },
        ["@variable.member.python"] = { fg = palette.brights.white },
        ["@type.builtin.python"] = { link = "@constant" },
        ["@variable.builtin.python"] = { link = "@constant" },
        ["@module.python"] = {},
        ["@label.ruby"] = { fg = palette.normal },
        ["@string.special.symbol.ruby"] = { link = "@constant" },
        ["@module.elixir"] = { link = "@type" },
        ["@constant.builtin.rust"] = { fg = palette.ansi.magenta },
        ["@module.rust"] = {},
        ["@keyword.directive.rust"] = { fg = palette.normal },
        ["@keyword.storage.lifetime.rust"] = { link = "@tag.rust" },
        ["@keyword.storage.lifetime.punctuation.rust"] = { link = "@markup.list.rust" },
        ["@property.scss"] = { link = "@constant" },
        ["@variable.scss"] = { link = "@variable.parameter" },
        ["@variable.member.sql"] = { link = "@constant" },
        ["@type.sql"] = { link = "@variable" },
        ["@variable.sql"] = { link = "@constant" },
        ["@variable.parameter.vimdoc"] = { fg = palette.ansi.magenta },
        ["@label.vimdoc"] = { link = "@keyword" },
        ["@property.yaml"] = { link = "@tag" },
        ["@variable"] = { fg = palette.normal },
        ["@variable.builtin"] = { fg = palette.ansi.magenta },
        ["@variable.parameter"] = { fg = palette.normal },
        ["@variable.parameter.builtin"] = { fg = palette.ansi.magenta },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { bold = true, fg = palette.brights.white },
        ["@module"] = { fg = palette.ansi.blue },
        ["@module.builtin"] = { fg = palette.brights.white },
        ["@label"] = { link = "@tag" },
        ["@string"] = { link = "String" },
        ["@keyword.exception"] = { fg = palette.ansi.magenta },
        ["@keyword.function"] = { bold = true, fg = palette.normal },
        ["@keyword.operator"] = { fg = palette.ansi.magenta },
        ["@string.regexp"] = { fg = palette.ansi.yellow },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.escape"] = { fg = palette.ansi.yellow },
        ["@string.special.url"] = { underline = true, italic = true, fg = palette.normal },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@type"] = { fg = palette.brights.blue },
        ["@type.builtin"] = { italic = true, fg = palette.ansi.blue },
        ["@attribute"] = { link = "Constant" },
        ["@attribute.builtin"] = { link = "Special" },
        ["@property"] = { link = "@variable.member" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { fg = palette.ansi.magenta },
        ["@constructor"] = { fg = palette.ansi.magenta },
        ["@operator"] = { link = "Operator" },
    },

    fzf_lua = {
        FzfLuaNormal = { link = "Normal" },
        FzfLuaBorder = { link = "Normal" },
        FzfLuaCursor = { link = "Cursor" },
        FzfLuaCursorLine = { link = "CursorLine" },
        FzfLuaCursorLineNr = { link = "CursorLineNr" },
        FzfLuaSearch = { link = "IncSearch" },
        FzfLuaTitle = { link = "Title" },
        FzfLuaScrollBorderEmpty = { link = "FzfLuaBorder" },
        FzfLuaHelpBorder = { link = "FzfLuaBorder" },
        FzfLuaScrollFloatFull = { link = "PmenuThumb" },
        FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
        FzfLuaScrollBorderFull = { link = "FzfLuaBorder" },
        FzfLuaHelpNormal = { link = "FzfLuaNormal" },
    },

    gitsigns = {
        GitSignsAdd = { fg = palette.brights.green },
        GitSignsDelete = { fg = palette.brights.red },
        GitSignsChange = { fg = palette.dark.yellow },
        GitSignsChangedelete = { link = "GitSignsChange" },
        GitSignsTopdelete = { link = "GitSignsDelete" },
        GitSignsUntracked = { link = "GitSignsAdd" },
        GitSignsAddNr = { link = "GitSignsAdd" },
        GitSignsChangeNr = { link = "GitSignsChange" },
        GitSignsDeleteNr = { link = "GitSignsDelete" },
        GitSignsChangedeleteNr = { link = "GitSignsChangeNr" },
        GitSignsTopdeleteNr = { link = "GitSignsDeleteNr" },
        GitSignsUntrackedNr = { link = "GitSignsAddNr" },
        GitSignsAddLn = { link = "DiffAdd" },
        GitSignsChangeLn = { link = "DiffChange" },
        GitSignsChangedeleteLn = { link = "GitSignsChangeLn" },
        GitSignsTopdeleteLn = { link = "GitSignsDeleteLn" },
        GitSignsDeleteLn = {},
        GitSignsUntrackedLn = { link = "GitSignsAddLn" },
        GitSignsAddCul = { link = "GitSignsAdd" },
        GitSignsChangeCul = { link = "GitSignsChange" },
        GitSignsDeleteCul = { link = "GitSignsDelete" },
        GitSignsChangedeleteCul = { link = "GitSignsChangeCul" },
        GitSignsTopdeleteCul = { link = "GitSignsDeleteCul" },
        GitSignsUntrackedCul = { link = "GitSignsAddCul" },
        GitSignsStagedAdd = { fg = palette.dark.green },
        GitSignsStagedChange = { fg = palette.dark.yellow },
        GitSignsStagedDelete = { fg = palette.dark.red },
        GitSignsStagedChangedelete = { fg = palette.dark.yellow },
        GitSignsStagedTopdelete = { fg = palette.dark.red },
        GitSignsStagedUntracked = { fg = palette.dark.green },
        GitSignsStagedAddNr = { fg = palette.dark.green },
        GitSignsStagedChangeNr = { fg = palette.dark.yellow },
        GitSignsStagedDeleteNr = { fg = palette.dark.red },
        GitSignsStagedChangedeleteNr = { fg = palette.dark.yellow },
        GitSignsStagedTopdeleteNr = { fg = palette.dark.red },
        GitSignsStagedUntrackedNr = { fg = palette.dark.green },
        GitSignsStagedAddLn = { fg = palette.dark.green, bg = palette.light.green },
        GitSignsStagedChangeLn = { fg = palette.dark.yellow, bg = palette.light.yellow },
        GitSignsStagedChangedeleteLn = { fg = palette.dark.yellow, bg = palette.light.yellow },
        GitSignsStagedTopdeleteLn = {},
        GitSignsStagedUntrackedLn = { fg = palette.dark.green, bg = palette.light.green },
        GitSignsStagedAddCul = { fg = palette.dark.green },
        GitSignsStagedChangeCul = { fg = palette.dark.yellow },
        GitSignsStagedDeleteCul = { fg = palette.dark.red },
        GitSignsStagedChangedeleteCul = { fg = palette.dark.yellow },
        GitSignsStagedTopdeleteCul = { fg = palette.dark.red },
        GitSignsStagedUntrackedCul = { fg = palette.dark.green },
        GitSignsAddPreview = { link = "DiffAdd" },
        GitSignsDeletePreview = { link = "DiffDelete" },
        GitSignsNoEOLPreview = { link = "Constant" },
        GitSignsCurrentLineBlame = { link = "NonText" },
        GitSignsAddInline = { link = "TermCursor" },
        GitSignsDeleteInline = { link = "TermCursor" },
        GitSignsChangeInline = { link = "TermCursor" },
        GitSignsAddLnInline = { link = "GitSignsAddInline" },
        GitSignsChangeLnInline = { link = "GitSignsChangeInline" },
        GitSignsDeleteLnInline = { link = "GitSignsDeleteInline" },
        GitSignsDeleteVirtLn = { link = "DiffDelete" },
        GitSignsDeleteVirtLnInLine = { link = "GitSignsDeleteLnInline" },
        GitSignsVirtLnum = { link = "GitSignsDeleteVirtLn" },
    },

    rainbow = {
        RainbowRed = { fg = palette.extra.gray1 },
        RainbowYellow = { fg = palette.extra.gray1 },
        RainbowBlue = { fg = palette.extra.gray1 },
        RainbowOrange = { fg = palette.extra.gray1 },
        RainbowGreen = { fg = palette.extra.gray1 },
        RainbowViolet = { fg = palette.extra.gray1 },
        RainbowCyan = { fg = palette.extra.gray1 },

        RainbowDelimiterRed = { fg = palette.rainbow.red },
        RainbowDelimiterOrange = { fg = palette.rainbow.orange },
        RainbowDelimiterYellow = { fg = palette.rainbow.yellow },
        RainbowDelimiterGreen = { fg = palette.rainbow.green },
        RainbowDelimiterCyan = { fg = palette.rainbow.cyan },
        RainbowDelimiterBlue = { fg = palette.rainbow.blue },
        RainbowDelimiterViolet = { fg = palette.rainbow.violet },
    },

    indent_blankline = {
        IblIndent = { fg = palette.extra.gray4 },
        IblWhitespace = { fg = palette.extra.gray4 },
        IblScope = { fg = palette.brights.black },
        ["@ibl"] = {},
        ["@ibl.indent.char.1"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.indent.char.2"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.indent.char.3"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.indent.char.4"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.indent.char.5"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.indent.char.6"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.indent.char.7"] = { nocombine = true, fg = palette.extra.gray1 },
        ["@ibl.whitespace.char.1"] = { nocombine = true, fg = palette.extra.gray4 },
        ["@ibl.scope.char.1"] = { nocombine = true, fg = palette.brights.black },
        ["@ibl.scope.underline.1"] = { underline = true, sp = palette.brights.black },
    },

    blink_cmp = {
        BlinkCmpLabel = { link = "CmpItemAbbr" },
        BlinkCmpLabelDeprecated = { link = "CmpItemAbbrDeprecated" },
        BlinkCmpLabelDetail = { link = "CmpItemMenu" },
        BlinkCmpLabelDescription = { link = "CmpItemMenu" },
        CmpItemKind = {},
        BlinkCmpKind = { link = "CmpItemKind" },
        BlinkCmpSource = { link = "CmpItemMenu" },
        CmpItemKindText = {},
        BlinkCmpKindMethod = { link = "CmpItemKindMethod" },
        BlinkCmpKindFunction = { link = "CmpItemKindFunction" },
        BlinkCmpKindConstructor = { link = "CmpItemKindConstructor" },
        BlinkCmpKindField = { link = "CmpItemKindField" },
        BlinkCmpKindVariable = { link = "CmpItemKindVariable" },
        BlinkCmpKindClass = { link = "CmpItemKindClass" },
        BlinkCmpKindInterface = { link = "CmpItemKindInterface" },
        BlinkCmpKindModule = { link = "CmpItemKindModule" },
        BlinkCmpKindProperty = { link = "CmpItemKindProperty" },
        BlinkCmpKindUnit = { link = "CmpItemKindUnit" },
        BlinkCmpKindValue = { link = "CmpItemKindValue" },
        BlinkCmpKindEnum = { link = "CmpItemKindEnum" },
        BlinkCmpKindKeyword = { link = "CmpItemKindKeyword" },
        BlinkCmpKindSnippet = { link = "CmpItemKindSnippet" },
        CmpItemKindColor = {},
        BlinkCmpKindColor = { link = "CmpItemKindColor" },
        CmpItemKindFile = {},
        BlinkCmpKindFile = { link = "CmpItemKindFile" },
        BlinkCmpKindReference = { link = "CmpItemKindReference" },
        CmpItemKindFolder = {},
        BlinkCmpKindFolder = { link = "CmpItemKindFolder" },
        BlinkCmpKindEnumMember = { link = "CmpItemKindEnumMember" },
        BlinkCmpKindConstant = { link = "CmpItemKindConstant" },
        BlinkCmpKindStruct = { link = "CmpItemKindStruct" },
        BlinkCmpKindEvent = { link = "CmpItemKindEvent" },
        BlinkCmpKindOperator = { link = "CmpItemKindOperator" },
        BlinkCmpKindTypeParameter = { link = "CmpItemKindTypeParameter" },
        BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
        BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
        CmpGhostText = {},
        BlinkCmpGhostText = { link = "CmpGhostText" },
        BlinkCmpMenuBorder = { link = "Pmenu" },
        BlinkCmpMenuSelection = { link = "PmenuSel" },
        BlinkCmpDoc = { link = "NormalFloat" },
        BlinkCmpDocBorder = { link = "NormalFloat" },
        BlinkCmpDocSeparator = { link = "NormalFloat" },
        BlinkCmpDocCursorLine = { link = "Visual" },
    },
}

return M.apply_highlight()
