vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
end
vim.g.colors_name = "aqua"

local function set_hl(group, options)
    local hl = vim.api.nvim_set_hl
    hl(0, group, options)
end

local palette = require("palette")

local function lualine()
    set_hl('lualine_transparent', { fg = palette.normal, bg = none })
    set_hl('lualine_b_command', { fg = palette.normal, bg = none })
    set_hl('lualine_a_command', { fg = palette.normal, bg = none })
    set_hl('lualine_c_command', { fg = palette.normal, bg = none })
    set_hl('lualine_b_terminal', { fg = palette.normal, bg = none })
    set_hl('lualine_a_terminal', { fg = palette.normal, bg = none })
    set_hl('lualine_c_terminal', { fg = palette.normal, bg = none })
    set_hl('lualine_b_normal', { fg = palette.normal, bg = none })
    set_hl('lualine_a_normal', { fg = palette.normal, bg = none })
    set_hl('lualine_c_normal', { fg = palette.normal, bg = none })
    set_hl('lualine_b_visual', { fg = palette.normal, bg = palette.light.blue })
    set_hl('lualine_a_visual', { fg = palette.normal, bg = palette.light.blue })
    set_hl('lualine_c_visual', { fg = palette.normal, bg = palette.light.blue })
    set_hl('lualine_b_replace', { fg = palette.normal, bg = palette.light.red })
    set_hl('lualine_a_replace', { fg = palette.normal, bg = palette.light.red })
    set_hl('lualine_c_replace', { fg = palette.normal, bg = palette.light.red })
    set_hl('lualine_b_insert', { fg = palette.normal, bg = palette.light.green })
    set_hl('lualine_a_insert', { fg = palette.normal, bg = palette.light.green })
    set_hl('lualine_c_insert', { fg = palette.normal, bg = palette.light.green })
    set_hl('lualine_b_inactive', { fg = palette.normal, bg = none })
    set_hl('lualine_a_inactive', { fg = palette.normal, bg = none })
    set_hl('lualine_c_inactive', { fg = palette.normal, bg = none })
    set_hl('lualine_b_diff_added_normal', { fg = palette.ansi.green, bg = none })
    set_hl('lualine_b_diff_added_insert', { fg = palette.ansi.green, bg = palette.light.green })
    set_hl('lualine_b_diff_added_visual', { fg = palette.ansi.green, bg = palette.light.blue })
    set_hl('lualine_b_diff_added_replace', { fg = palette.ansi.green, bg = palette.light.red })
    set_hl('lualine_b_diff_added_command', { fg = palette.ansi.green, bg = none })
    set_hl('lualine_b_diff_added_terminal', { fg = palette.ansi.green, bg = none })
    set_hl('lualine_b_diff_added_inactive', { fg = palette.ansi.green, bg = none })
    set_hl('lualine_b_diff_modified_normal', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_b_diff_modified_insert', { fg = palette.ansi.yellow, bg = palette.light.green })
    set_hl('lualine_b_diff_modified_visual', { fg = palette.ansi.yellow, bg = palette.light.blue })
    set_hl('lualine_b_diff_modified_replace', { fg = palette.ansi.yellow, bg = palette.light.red })
    set_hl('lualine_b_diff_modified_command', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_b_diff_modified_terminal', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_b_diff_modified_inactive', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_b_diff_removed_normal', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_b_diff_removed_insert', { fg = palette.ansi.red, bg = palette.light.green })
    set_hl('lualine_b_diff_removed_visual', { fg = palette.ansi.red, bg = palette.light.blue })
    set_hl('lualine_b_diff_removed_replace', { fg = palette.ansi.red, bg = palette.light.red })
    set_hl('lualine_b_diff_removed_command', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_b_diff_removed_terminal', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_b_diff_removed_inactive', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_x_diagnostics_error_normal', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_x_diagnostics_error_insert', { fg = palette.ansi.red, bg = palette.light.green })
    set_hl('lualine_x_diagnostics_error_visual', { fg = palette.ansi.red, bg = palette.light.blue })
    set_hl('lualine_x_diagnostics_error_replace', { fg = palette.ansi.red, bg = palette.light.red })
    set_hl('lualine_x_diagnostics_error_command', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_x_diagnostics_error_terminal', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_x_diagnostics_error_inactive', { fg = palette.ansi.red, bg = none })
    set_hl('lualine_x_diagnostics_warn_normal', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_x_diagnostics_warn_insert', { fg = palette.ansi.yellow, bg = palette.light.green })
    set_hl('lualine_x_diagnostics_warn_visual', { fg = palette.ansi.yellow, bg = palette.light.blue })
    set_hl('lualine_x_diagnostics_warn_replace', { fg = palette.ansi.yellow, bg = palette.light.red })
    set_hl('lualine_x_diagnostics_warn_command', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_x_diagnostics_warn_terminal', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_x_diagnostics_warn_inactive', { fg = palette.ansi.yellow, bg = none })
    set_hl('lualine_x_diagnostics_info_normal', { fg = palette.ansi.blue, bg = none })
    set_hl('lualine_x_diagnostics_info_insert', { fg = palette.ansi.blue, bg = palette.light.green })
    set_hl('lualine_x_diagnostics_info_visual', { fg = palette.ansi.blue, bg = palette.light.blue })
    set_hl('lualine_x_diagnostics_info_replace', { fg = palette.ansi.blue, bg = palette.light.red })
    set_hl('lualine_x_diagnostics_info_command', { fg = palette.ansi.blue, bg = none })
    set_hl('lualine_x_diagnostics_info_terminal', { fg = palette.ansi.blue, bg = none })
    set_hl('lualine_x_diagnostics_info_inactive', { fg = palette.ansi.blue, bg = none })
    set_hl('lualine_x_diagnostics_hint_normal', { fg = palette.ansi.cyan, bg = none })
    set_hl('lualine_x_diagnostics_hint_insert', { fg = palette.ansi.cyan, bg = palette.light.green })
    set_hl('lualine_x_diagnostics_hint_visual', { fg = palette.ansi.cyan, bg = palette.light.blue })
    set_hl('lualine_x_diagnostics_hint_replace', { fg = palette.ansi.cyan, bg = palette.light.red })
    set_hl('lualine_x_diagnostics_hint_command', { fg = palette.ansi.cyan, bg = none })
    set_hl('lualine_x_diagnostics_hint_terminal', { fg = palette.ansi.cyan, bg = none })
    set_hl('lualine_x_diagnostics_hint_inactive', { fg = palette.ansi.cyan, bg = none })
end

local function default()
    set_hl('SpecialKey', { link = 'NonText' })
    set_hl('EndOfBuffer', { fg = palette.normal })
    set_hl('TermCursor', { reverse = true })
    set_hl('NonText', { fg = palette.extra.gray2 })
    set_hl('Directory', { fg = palette.ansi.yellow })
    set_hl('ErrorMsg', { fg = palette.ansi.red })
    set_hl('IncSearch', { fg = palette.ansi.black, bg = palette.dark.yellow })
    set_hl('Search', { bg = palette.light.yellow })
    set_hl('CurSearch', { link = 'IncSearch' })
    set_hl('MoreMsg', { bold = true, fg = palette.ansi.blue })
    set_hl('ModeMsg', { bold = true, fg = palette.ansi.yellow })
    set_hl('LineNr', { fg = palette.brights.black })
    set_hl('LineNrAbove', { link = 'LineNr' })
    set_hl('LineNrBelow', { link = 'LineNr' })
    set_hl('CursorLineNr', { bg = palette.extra.gray0 })
    set_hl('CursorLineSign', { bg = palette.extra.gray0 })
    set_hl('CursorLineFold', { link = 'FoldColumn' })
    set_hl('Question', { link = 'MoreMsg' })
    set_hl('StatusLine', { fg = palette.normal, bg = none })
    set_hl('StatusLineNC', { underline = true, fg = palette.extra.bg1, bg = palette.extra.bg1, sp = palette.extra.bg1 })
    set_hl('WinSeparator', { fg = palette.extra.pencilGray })
    set_hl('VertSplit', { fg = palette.extra.pencilGray })
    set_hl('Title', { bold = true, fg = palette.brights.white })
    set_hl('Visual', { bg = palette.extra.gray1 })
    set_hl('VisualNC', {})
    set_hl('WarningMsg', { fg = palette.ansi.yellow })
    set_hl('WildMenu', { link = 'Pmenu' })
    set_hl('Folded', { fg = palette.brights.black, bg = palette.extra.bg1 })
    set_hl('FoldColumn', { fg = palette.brights.black })
    set_hl('DiffAdd', { link = 'diffAdded' })
    set_hl('DiffChange', { link = 'diffChanged' })
    set_hl('DiffDelete', { link = 'diffRemoved' })
    set_hl('DiffText', { fg = palette.normal, bg = none })
    set_hl('SignColumn', { fg = palette.brights.black })
    set_hl('Conceal', { fg = palette.brights.black })
    set_hl('SpellBad', { undercurl = true, sp = palette.ansi.red })
    set_hl('SpellCap', { undercurl = true, sp = palette.ansi.yellow })
    set_hl('SpellRare', { undercurl = true, sp = palette.ansi.blue })
    set_hl('SpellLocal', { undercurl = true, sp = palette.ansi.blue })
    set_hl('Pmenu', { fg = palette.normal, bg = palette.extra.gray1 })
    set_hl('PmenuSel', { bg = palette.extra.gray4 })
    set_hl('PmenuMatch', { bold = true })
    set_hl('PmenuMatchSel', { bold = true })
    set_hl('PmenuKind', { link = 'Pmenu' })
    set_hl('PmenuKindSel', { link = 'PmenuSel' })
    set_hl('PmenuExtra', { link = 'Pmenu' })
    set_hl('PmenuExtraSel', { link = 'PmenuSel' })
    set_hl('PmenuSbar', { link = 'Pmenu' })
    set_hl('PmenuThumb', { bg = none })
    set_hl('TabLine', { fg = palette.normal, bg = palette.extra.gray4 })
    set_hl('TabLineSel', { fg = none, bg = palette.brights.black })
    set_hl('TabLineFill', {})
    set_hl('CursorColumn', { link = 'CursorLine' })
    set_hl('CursorLine', { bg = palette.extra.gray0 })
    set_hl('ColorColumn', { bg = palette.extra.bg1 })
    set_hl('QuickFixLine', { link = 'CursorLine' })
    set_hl('Whitespace', { fg = palette.extra.gray4 })
    set_hl('NormalNC', { fg = palette.normal })
    set_hl('MsgSeparator', { link = 'StatusLine' })
    set_hl('NormalFloat', {})
    set_hl('MsgArea', {})
    set_hl('FloatBorder', { fg = palette.extra.gray2 })
    set_hl('WinBar', { bold = true, fg = palette.brights.black })
    set_hl('WinBarNC', { bold = true, fg = palette.brights.black })
    set_hl('Cursor', { fg = none, bg = palette.dark.blue })
    set_hl('FloatTitle', {})
    set_hl('FloatFooter', { link = 'FloatTitle' })
    set_hl('StatusLineTerm', { link = 'StatusLine' })
    set_hl('StatusLineTermNC', { link = 'StatusLineNC' })
    set_hl('RedrawDebugNormal', { reverse = true })
    set_hl('Underlined', { underline = true })
    set_hl('lCursor', { link = 'Cursor' })
    set_hl('CursorIM', { link = 'Cursor' })
    set_hl('ComplMatchIns', {})
    set_hl('Substitute', { fg = palette.ansi.black, bg = palette.ansi.red })
    set_hl('VisualNOS', { link = 'Visual' })
    set_hl('Normal', { fg = palette.normal })
    set_hl('Character', { link = 'String' })
    set_hl('Constant', { bold = true, fg = palette.normal })
    set_hl('Number', { fg = palette.normal })
    set_hl('Boolean', { link = 'Number' })
    set_hl('Float', { link = 'Number' })
    set_hl('Conditional', { fg = palette.normal })
    set_hl('Statement', { bold = true, fg = palette.normal })
    set_hl('Repeat', { link = 'Conditional' })
    set_hl('Label', { link = 'Conditional' })
    set_hl('Keyword', { bold = true, fg = palette.normal })
    set_hl('Exception', { link = 'Keyword' })
    set_hl('Include', { link = 'PreProc' })
    set_hl('PreProc', { fg = palette.normal })
    set_hl('Define', { link = 'PreProc' })
    set_hl('Macro', { link = 'PreProc' })
    set_hl('PreCondit', { link = 'PreProc' })
    set_hl('StorageClass', { link = 'Type' })
    set_hl('Type', { italic = true, fg = palette.brights.white })
    set_hl('Structure', { link = 'Type' })
    set_hl('Typedef', { link = 'Type' })
    set_hl('Tag', { link = 'Special' })
    set_hl('Special', { fg = palette.normal, bold = true })
    set_hl('SpecialChar', { link = 'Special' })
    set_hl('SpecialComment', { link = 'Special' })
    set_hl('Debug', { link = 'Special' })
    set_hl('Ignore', { link = 'Normal' })
    set_hl('LspCodeLens', { fg = '#57606a' })
    set_hl('LspCodeLensSeparator', { fg = '#57606a' })
    set_hl('LspInlayHint', { fg = '#57606a', bg = '#f1f1f2' })
    set_hl('LspReferenceRead', { bg = '#dae9f9' })
    set_hl('LspReferenceText', { bg = '#dae9f9' })
    set_hl('LspReferenceWrite', { bg = '#dae9f9' })
    set_hl('LspReferenceTarget', { link = 'LspReferenceText' })
    set_hl('LspSignatureActiveParameter', { fg = '#c2e2ff' })
    set_hl('SnippetTabstop', { link = 'Visual' })
    set_hl('DiagnosticFloatingError', { link = 'DiagnosticError' })
    set_hl('DiagnosticError', { fg = '#d1242f' })
    set_hl('DiagnosticFloatingWarn', { link = 'DiagnosticWarn' })
    set_hl('DiagnosticWarn', { fg = '#9a6700' })
    set_hl('DiagnosticFloatingInfo', { link = 'DiagnosticInfo' })
    set_hl('DiagnosticInfo', { fg = palette.ansi.cyan })
    set_hl('DiagnosticFloatingHint', { link = 'DiagnosticHint' })
    set_hl('DiagnosticHint', { fg = '#007070' })
    set_hl('DiagnosticFloatingOk', { link = 'DiagnosticOk' })
    set_hl('DiagnosticOk', { fg = 'NvimDarkGreen' })
    set_hl('DiagnosticVirtualTextError', { fg = '#d1242f' })
    set_hl('DiagnosticVirtualTextWarn', { fg = '#9a6700' })
    set_hl('DiagnosticVirtualTextInfo', { fg = palette.ansi.cyan })
    set_hl('DiagnosticVirtualTextHint', { fg = '#d0d7de' })
    set_hl('DiagnosticVirtualTextOk', { link = 'DiagnosticOk' })
    set_hl('DiagnosticVirtualLinesError', { link = 'DiagnosticError' })
    set_hl('DiagnosticVirtualLinesWarn', { link = 'DiagnosticWarn' })
    set_hl('DiagnosticVirtualLinesInfo', { link = 'DiagnosticInfo' })
    set_hl('DiagnosticVirtualLinesHint', { link = 'DiagnosticHint' })
    set_hl('DiagnosticVirtualLinesOk', { link = 'DiagnosticOk' })
    set_hl('DiagnosticSignError', { link = 'DiagnosticError' })
    set_hl('DiagnosticSignWarn', { link = 'DiagnosticWarn' })
    set_hl('DiagnosticSignInfo', { link = 'DiagnosticInfo' })
    set_hl('DiagnosticSignHint', { link = 'DiagnosticHint' })
    set_hl('DiagnosticSignOk', { link = 'DiagnosticOk' })
    set_hl('DiagnosticUnnecessary', { link = 'Comment' })
    set_hl('Comment', { italic = true, nocombine = true, fg = '#57606a' })
    set_hl('String', { fg = '#1e763c' })
    set_hl('Function', { fg = '#007070' })
    set_hl('Operator', { fg = '#2c363c' })
    set_hl('Delimiter', { link = 'Special' })
    set_hl('Todo', { fg = '#ffffff', bg = palette.ansi.cyan })
    set_hl('Added', { fg = '#1a7f37', bg = '#b8d0bf' })
    set_hl('Removed', { fg = '#d1242f', bg = '#e4b7be' })
    set_hl('Changed', { fg = '#9a6700', bg = '#d8cab3' })
    set_hl('DiagnosticDeprecated', { strikethrough = true, sp = 'NvimDarkRed' })
    set_hl('MatchParen', { bold = true, fg = '#1f2328', bg = '#bbdfff' })
    set_hl('Error', { fg = '#d1242f' })
    set_hl('DiagnosticUnderlineError', { undercurl = true, sp = '#d1242f' })
    set_hl('DiagnosticUnderlineWarn', { undercurl = true, sp = '#9a6700' })
    set_hl('DiagnosticUnderlineInfo', { undercurl = true, sp = palette.ansi.cyan })
    set_hl('DiagnosticUnderlineHint', { undercurl = true, sp = '#d0d7de' })
    set_hl('DiagnosticUnderlineOk', { underline = true, sp = 'NvimDarkGreen' })
    set_hl('NvimInternalError', { fg = 'Red', bg = 'Red' })
    set_hl('NvimAssignment', { link = 'Operator' })
    set_hl('NvimPlainAssignment', { link = 'NvimAssignment' })
    set_hl('NvimAugmentedAssignment', { link = 'NvimAssignment' })
    set_hl('NvimAssignmentWithAddition', { link = 'NvimAugmentedAssignment' })
    set_hl('NvimAssignmentWithSubtraction', { link = 'NvimAugmentedAssignment' })
    set_hl('NvimAssignmentWithConcatenation', { link = 'NvimAugmentedAssignment' })
    set_hl('NvimOperator', { link = 'Operator' })
    set_hl('NvimUnaryOperator', { link = 'NvimOperator' })
    set_hl('NvimUnaryPlus', { link = 'NvimUnaryOperator' })
    set_hl('NvimUnaryMinus', { link = 'NvimUnaryOperator' })
    set_hl('NvimNot', { link = 'NvimUnaryOperator' })
    set_hl('NvimBinaryOperator', { link = 'NvimOperator' })
    set_hl('NvimComparison', { link = 'NvimBinaryOperator' })
    set_hl('NvimComparisonModifier', { link = 'NvimComparison' })
    set_hl('NvimBinaryPlus', { link = 'NvimBinaryOperator' })
    set_hl('NvimBinaryMinus', { link = 'NvimBinaryOperator' })
    set_hl('NvimConcat', { link = 'NvimBinaryOperator' })
    set_hl('NvimConcatOrSubscript', { link = 'NvimConcat' })
    set_hl('NvimOr', { link = 'NvimBinaryOperator' })
    set_hl('NvimAnd', { link = 'NvimBinaryOperator' })
    set_hl('NvimMultiplication', { link = 'NvimBinaryOperator' })
    set_hl('NvimDivision', { link = 'NvimBinaryOperator' })
    set_hl('NvimMod', { link = 'NvimBinaryOperator' })
    set_hl('NvimTernary', { link = 'NvimOperator' })
    set_hl('NvimTernaryColon', { link = 'NvimTernary' })
    set_hl('NvimParenthesis', { link = 'Delimiter' })
    set_hl('NvimLambda', { link = 'NvimParenthesis' })
    set_hl('NvimNestingParenthesis', { link = 'NvimParenthesis' })
    set_hl('NvimCallingParenthesis', { link = 'NvimParenthesis' })
    set_hl('NvimSubscript', { link = 'NvimParenthesis' })
    set_hl('NvimSubscriptBracket', { link = 'NvimSubscript' })
    set_hl('NvimSubscriptColon', { link = 'NvimSubscript' })
    set_hl('NvimCurly', { link = 'NvimSubscript' })
    set_hl('NvimContainer', { link = 'NvimParenthesis' })
    set_hl('NvimDict', { link = 'NvimContainer' })
    set_hl('NvimList', { link = 'NvimContainer' })
    set_hl('NvimIdentifier', { link = 'Identifier' })
    set_hl('NvimIdentifierScope', { link = 'NvimIdentifier' })
    set_hl('NvimIdentifierScopeDelimiter', { link = 'NvimIdentifier' })
    set_hl('NvimIdentifierName', { link = 'NvimIdentifier' })
    set_hl('NvimIdentifierKey', { link = 'NvimIdentifier' })
    set_hl('NvimColon', { link = 'Delimiter' })
    set_hl('NvimComma', { link = 'Delimiter' })
    set_hl('NvimArrow', { link = 'Delimiter' })
    set_hl('NvimRegister', { link = 'SpecialChar' })
    set_hl('NvimNumber', { link = 'Number' })
    set_hl('NvimFloat', { link = 'NvimNumber' })
    set_hl('NvimNumberPrefix', { link = 'Type' })
    set_hl('NvimOptionSigil', { link = 'Type' })
    set_hl('NvimOptionName', { link = 'NvimIdentifier' })
    set_hl('NvimOptionScope', { link = 'NvimIdentifierScope' })
    set_hl('NvimOptionScopeDelimiter', { link = 'NvimIdentifierScopeDelimiter' })
    set_hl('NvimEnvironmentSigil', { link = 'NvimOptionSigil' })
    set_hl('NvimEnvironmentName', { link = 'NvimIdentifier' })
    set_hl('NvimString', { link = 'String' })
    set_hl('NvimStringBody', { link = 'NvimString' })
    set_hl('NvimStringQuote', { link = 'NvimString' })
    set_hl('NvimStringSpecial', { link = 'SpecialChar' })
    set_hl('NvimSingleQuote', { link = 'NvimStringQuote' })
    set_hl('NvimSingleQuotedBody', { link = 'NvimStringBody' })
    set_hl('NvimSingleQuotedQuote', { link = 'NvimStringSpecial' })
    set_hl('NvimDoubleQuote', { link = 'NvimStringQuote' })
    set_hl('NvimDoubleQuotedBody', { link = 'NvimStringBody' })
    set_hl('NvimDoubleQuotedEscape', { link = 'NvimStringSpecial' })
    set_hl('NvimFigureBrace', { link = 'NvimInternalError' })
    set_hl('NvimSingleQuotedUnknownEscape', { link = 'NvimInternalError' })
    set_hl('NvimSpacing', { link = 'Normal' })
    set_hl('NvimInvalidSingleQuotedUnknownEscape', { link = 'NvimInternalError' })
    set_hl('NvimInvalid', { link = 'Error' })
    set_hl('NvimInvalidAssignment', { link = 'NvimInvalid' })
    set_hl('NvimInvalidPlainAssignment', { link = 'NvimInvalidAssignment' })
    set_hl('NvimInvalidAugmentedAssignment', { link = 'NvimInvalidAssignment' })
    set_hl('NvimInvalidAssignmentWithAddition', { link = 'NvimInvalidAugmentedAssignment' })
    set_hl('NvimInvalidAssignmentWithSubtraction', { link = 'NvimInvalidAugmentedAssignment' })
    set_hl('NvimInvalidAssignmentWithConcatenation', { link = 'NvimInvalidAugmentedAssignment' })
    set_hl('NvimInvalidOperator', { link = 'NvimInvalid' })
    set_hl('NvimInvalidUnaryOperator', { link = 'NvimInvalidOperator' })
    set_hl('NvimInvalidUnaryPlus', { link = 'NvimInvalidUnaryOperator' })
    set_hl('NvimInvalidUnaryMinus', { link = 'NvimInvalidUnaryOperator' })
    set_hl('NvimInvalidNot', { link = 'NvimInvalidUnaryOperator' })
    set_hl('NvimInvalidBinaryOperator', { link = 'NvimInvalidOperator' })
    set_hl('NvimInvalidComparison', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidComparisonModifier', { link = 'NvimComparison' })
    set_hl('NvimInvalidBinaryPlus', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidBinaryMinus', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidConcat', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidConcatOrSubscript', { link = 'NvimInvalidConcat' })
    set_hl('NvimInvalidOr', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidAnd', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidMultiplication', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidDivision', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidMod', { link = 'NvimBinaryOperator' })
    set_hl('NvimInvalidTernary', { link = 'NvimOperator' })
    set_hl('NvimInvalidTernaryColon', { link = 'NvimInvalidTernary' })
    set_hl('NvimInvalidDelimiter', { link = 'NvimInvalid' })
    set_hl('NvimInvalidParenthesis', { link = 'NvimInvalidDelimiter' })
    set_hl('NvimInvalidLambda', { link = 'NvimInvalidParenthesis' })
    set_hl('NvimInvalidNestingParenthesis', { link = 'NvimInvalidParenthesis' })
    set_hl('NvimInvalidCallingParenthesis', { link = 'NvimInvalidParenthesis' })
    set_hl('NvimInvalidSubscript', { link = 'NvimInvalidParenthesis' })
    set_hl('NvimInvalidSubscriptBracket', { link = 'NvimInvalidSubscript' })
    set_hl('NvimInvalidSubscriptColon', { link = 'NvimInvalidSubscript' })
    set_hl('NvimInvalidCurly', { link = 'NvimInvalidSubscript' })
    set_hl('NvimInvalidContainer', { link = 'NvimInvalidParenthesis' })
    set_hl('NvimInvalidDict', { link = 'NvimInvalidContainer' })
    set_hl('NvimInvalidList', { link = 'NvimInvalidContainer' })
    set_hl('NvimInvalidValue', { link = 'NvimInvalid' })
    set_hl('NvimInvalidIdentifier', { link = 'NvimInvalidValue' })
    set_hl('NvimInvalidIdentifierScope', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidIdentifierScopeDelimiter', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidIdentifierName', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidIdentifierKey', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidColon', { link = 'NvimInvalidDelimiter' })
    set_hl('NvimInvalidComma', { link = 'NvimInvalidDelimiter' })
    set_hl('NvimInvalidArrow', { link = 'NvimInvalidDelimiter' })
    set_hl('NvimInvalidRegister', { link = 'NvimInvalidValue' })
    set_hl('NvimInvalidNumber', { link = 'NvimInvalidValue' })
    set_hl('NvimInvalidFloat', { link = 'NvimInvalidNumber' })
    set_hl('NvimInvalidNumberPrefix', { link = 'NvimInvalidNumber' })
    set_hl('NvimInvalidOptionSigil', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidOptionName', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidOptionScope', { link = 'NvimInvalidIdentifierScope' })
    set_hl('NvimInvalidOptionScopeDelimiter', { link = 'NvimInvalidIdentifierScopeDelimiter' })
    set_hl('NvimInvalidEnvironmentSigil', { link = 'NvimInvalidOptionSigil' })
    set_hl('NvimInvalidEnvironmentName', { link = 'NvimInvalidIdentifier' })
    set_hl('NvimInvalidString', { link = 'NvimInvalidValue' })
    set_hl('NvimInvalidStringBody', { link = 'NvimStringBody' })
    set_hl('NvimInvalidStringQuote', { link = 'NvimInvalidString' })
    set_hl('NvimInvalidStringSpecial', { link = 'NvimStringSpecial' })
    set_hl('NvimInvalidSingleQuote', { link = 'NvimInvalidStringQuote' })
    set_hl('NvimInvalidSingleQuotedBody', { link = 'NvimInvalidStringBody' })
    set_hl('NvimInvalidSingleQuotedQuote', { link = 'NvimInvalidStringSpecial' })
    set_hl('NvimInvalidDoubleQuote', { link = 'NvimInvalidStringQuote' })
    set_hl('NvimInvalidDoubleQuotedBody', { link = 'NvimInvalidStringBody' })
    set_hl('NvimInvalidDoubleQuotedEscape', { link = 'NvimInvalidStringSpecial' })
    set_hl('NvimInvalidDoubleQuotedUnknownEscape', { link = 'NvimInvalidValue' })
    set_hl('NvimInvalidFigureBrace', { link = 'NvimInvalidDelimiter' })
    set_hl('NvimInvalidSpacing', { link = 'ErrorMsg' })
    set_hl('NvimDoubleQuotedUnknownEscape', { link = 'NvimInvalidValue' })
end

local function mini()
    set_hl('MiniPickCursor', { nocombine = true, blend = 100 })
    set_hl('MiniDepsChangeAdded', { link = 'diffAdded' })
    set_hl('MiniDepsChangeRemoved', { link = 'diffRemoved' })
    set_hl('MiniDepsHint', { link = 'DiagnosticHint' })
    set_hl('MiniDepsInfo', { link = 'DiagnosticInfo' })
    set_hl('MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
    set_hl('MiniDepsPlaceholder', { link = 'Comment' })
    set_hl('MiniDepsTitle', { link = 'Title' })
    set_hl('MiniDepsTitleError', { link = 'DiffDelete' })
    set_hl('MiniDepsTitleSame', { link = 'DiffText' })
    set_hl('MiniDepsTitleUpdate', { link = 'DiffAdd' })
    set_hl('MiniIconsAzure', { fg = palette.brights.white })
    set_hl('MiniIconsBlue', { fg = palette.ansi.blue })
    set_hl('MiniIconsCyan', { fg = palette.ansi.cyan })
    set_hl('MiniIconsGreen', { fg = palette.ansi.green })
    set_hl('MiniIconsGrey', { fg = palette.extra.gray1 })
    set_hl('MiniIconsOrange', { fg = palette.dark.yellow })
    set_hl('MiniIconsPurple', { fg = palette.dark.magenta })
    set_hl('MiniIconsRed', { fg = palette.dark.red })
    set_hl('MiniIconsYellow', { fg = palette.ansi.yellow })
    set_hl('MiniNotifyBorder', { fg = palette.extra.gray1 })
    set_hl('MiniNotifyNormal', { link = 'NormalFloat' })
    set_hl('MiniNotifyLspProgress', { link = 'MiniNotifyNormal' })
    set_hl('MiniNotifyTitle', { fg = '#e7e7e7' })
    set_hl('MiniPickPreviewLine', { link = 'CursorLine' })
    set_hl('MiniPickPreviewRegion', { link = 'IncSearch' })
    set_hl('MiniStarterCurrent', { nocombine = true })
    set_hl('MiniStarterFooter', { italic = true, fg = palette.extra.gray2 })
    set_hl('MiniStarterHeader', { fg = palette.ansi.cyan })
    set_hl('MiniStarterInactive', { link = 'Comment' })
    set_hl('MiniStarterItem', { link = 'Normal' })
    set_hl('MiniStarterItemBullet', { fg = '#d0d7de' })
    set_hl('MiniStarterItemPrefix', { fg = '#9a6700' })
    set_hl('MiniStarterSection', { link = 'Special' })
    set_hl('MiniStarterQuery', { fg = palette.ansi.cyan })
    set_hl('MiniStatuslineDevinfo', { fg = '#1f2328', bg = '#e7eaf0' })
    set_hl('MiniStatuslineFileinfo', { fg = '#1f2328', bg = '#e7eaf0' })
    set_hl('MiniStatuslineFilename', { fg = '#8f9193', bg = '#ffffff' })
    set_hl('MiniStatuslineInactive', { fg = '#8f9193', bg = '#f6f8fa' })
    set_hl('MiniStatuslineModeCommand', { bold = true, fg = '#ffffff', bg = '#a475f9' })
    set_hl('MiniStatuslineModeInsert', { bold = true, fg = '#ffffff', bg = '#116329' })
    set_hl('MiniStatuslineModeNormal', { bold = true, fg = '#ffffff', bg = palette.ansi.cyan })
    set_hl('MiniStatuslineModeOther', { bold = true, fg = '#ffffff' })
    set_hl('MiniStatuslineModeReplace', { bold = true, fg = '#ffffff', bg = '#cf222e' })
    set_hl('MiniStatuslineModeVisual', { bold = true, fg = '#ffffff', bg = '#4d2d00' })
    set_hl('MiniSurround', { link = 'IncSearch' })
    set_hl('MiniTablineCurrent', { bold = true, fg = '#f6f8fa', bg = '#59a8ff' })
    set_hl('MiniTablineFill', { link = 'TabLineFill' })
    set_hl('MiniTablineHidden', { fg = '#1f2328', bg = '#ffffff' })
    set_hl('MiniTablineModifiedCurrent', { bold = true, fg = '#59a8ff', bg = '#f6f8fa' })
    set_hl('MiniTablineModifiedHidden', { fg = '#ffffff', bg = '#1f2328' })
    set_hl('MiniTablineModifiedVisible', { fg = '#90c5ff', bg = '#f6f8fa' })
    set_hl('MiniTablineTabpagesection', { bold = true, bg = '#c2e2ff' })
    set_hl('MiniTablineVisible', { fg = '#f6f8fa', bg = '#90c5ff' })
    set_hl('MiniTestEmphasis', { bold = true })
    set_hl('MiniTestFail', { bold = true, fg = '#cf222e' })
    set_hl('MiniTestPass', { bold = true, fg = '#116329' })
    set_hl('MiniTrailspace', { bg = '#cf222e' })
end

local function neogit()
    set_hl('NeogitBranch', { fg = '#9a6700' })
    set_hl('NeogitRemote', { fg = '#d0d7de' })
    set_hl('NeogitHunkHeader', { fg = palette.ansi.cyan, bg = '#e7eaf0' })
    set_hl('NeogitHunkHeaderHighlight', { fg = palette.ansi.cyan, bg = '#dae9f9' })
    set_hl('NeogitDiffAdd', { fg = '#1a7f37' })
    set_hl('NeogitDiffDelete', { fg = '#d1242f' })
    set_hl('NeogitDiffAddHighlight', { bg = '#b8d0bf' })
    set_hl('NeogitDiffDeleteHighlight', { bg = '#e4b7be' })
    set_hl('NeogitDiffContextHighlight', { bg = '#f1f1f2' })
    set_hl('NeogitNotificationInfo', { fg = palette.ansi.cyan })
    set_hl('NeogitNotificationWarning', { fg = '#9a6700' })
    set_hl('NeogitNotificationError', { fg = '#d1242f' })
    set_hl('NormalSB', { fg = '#1f2328' })
    set_hl('NeoTreeNormal', { link = 'NormalSB' })
    set_hl('NeoTreeNormalNC', { link = 'NeoTreeNormal' })
    set_hl('NeoTreeTitleBar', { fg = '#ffffff', bg = '#2278de' })
    set_hl('NeoTreeEndOfBuffer', { fg = '#f6f8fa' })
    set_hl('NeoTreeIndentMarker', { fg = '#6e7781' })
    set_hl('NeoTreeRootName', { bold = true, fg = '#1f2328' })
    set_hl('NeoTreeDirectoryName', { fg = '#1f2328' })
    set_hl('NeoTreeDirectoryIcon', { fg = '#1f2328' })
    set_hl('NeoTreeDotfile', { fg = '#84b4ed' })
    set_hl('NeoTreeSymbolicLinkTarget', { fg = '#df9cc4' })
    set_hl('NeoTreeFileName', { fg = '#1f2328' })
    set_hl('NeoTreeFileNameOpened', { fg = '#218bff' })
    set_hl('NeoTreeDimText', { link = 'Conceal' })
    set_hl('NeoTreeGitModified', { fg = '#9a6700' })
    set_hl('NeoTreeGitAdded', { fg = '#1a7f37' })
    set_hl('NeoTreeGitDeleted', { fg = '#d1242f' })
    set_hl('NeoTreeGitConflict', { italic = true, fg = '#bc4c00' })
    set_hl('NeoTreeGitIgnored', { fg = '#6e7781' })
    set_hl('NeoTreeGitUntracked', { fg = '#32898f' })
end

set_hl('NotifyERRORTitle', { fg = '#cf222e' })
set_hl('NotifyWARNTitle', { fg = '#4d2d00' })
set_hl('NotifyINFOTitle', { fg = '#116329' })
set_hl('NotifyDEBUGTitle', { fg = '#1f2328' })
set_hl('NotifyTRACETitle', { fg = '#a475f9' })
set_hl('NotifyERRORIcon', { link = 'NotifyERRORTitle' })
set_hl('NotifyWARNIcon', { link = 'NotifyWARNTitle' })
set_hl('NotifyINFOIcon', { link = 'NotifyINFOTitle' })
set_hl('NotifyDEBUGIcon', { link = 'NotifyDEBUGTitle' })
set_hl('NotifyTRACEIcon', { link = 'NotifyTRACETitle' })
set_hl('NotifyERRORBorder', { link = 'NotifyERRORTitle' })
set_hl('NotifyWARNBorder', { link = 'NotifyWARNTitle' })
set_hl('NotifyINFOBorder', { link = 'NotifyINFOTitle' })
set_hl('NotifyDEBUGBorder', { link = 'NotifyDEBUGTitle' })
set_hl('NotifyTRACEBorder', { link = 'NotifyTRACETitle' })
set_hl('NotifyERRORBody', { link = 'NotifyERRORTitle' })
set_hl('NotifyWARNBody', { link = 'NotifyWARNTitle' })
set_hl('NotifyINFOBody', { link = 'NotifyINFOTitle' })
set_hl('NotifyDEBUGBody', { link = 'NotifyDEBUGTitle' })
set_hl('NotifyTRACEBody', { link = 'NotifyTRACETitle' })
set_hl('NvimTreeNormal', { link = 'NormalSB' })
set_hl('NvimTreeEndOfBuffer', { fg = '#f6f8fa' })
set_hl('NvimTreeRootFolder', { bold = true, fg = '#1f2328' })
set_hl('NvimTreeGitDirty', { fg = '#9a6700' })
set_hl('NvimTreeGitNew', { fg = '#1a7f37' })
set_hl('NvimTreeGitRenamed', { fg = '#8250df' })
set_hl('NvimTreeGitDeleted', { fg = '#d1242f' })
set_hl('NvimTreeGitIgnored', { fg = '#57606a' })
set_hl('NvimTreeSpecialFile', { underline = true, fg = '#4d2d00' })
set_hl('NvimTreeIndentMarker', { fg = '#57606a' })
set_hl('NvimTreeImageFile', { fg = '#633c01' })
set_hl('NvimTreeSymlink', { fg = '#8250df' })
set_hl('NvimTreeFolderName', { fg = '#1f2328' })
set_hl('NvimTreeOpenedFolderName', { bold = true, fg = '#1f2328' })
set_hl('NvimTreeOpenedFile', { fg = '#218bff' })
set_hl('diffAdded', { link = 'Added' })
set_hl('diffRemoved', { link = 'Removed' })
set_hl('diffChanged', { link = 'Changed' })
set_hl('htmlTag', { fg = '#015493' })
set_hl('NONE', {})

local function treesitter()
    set_hl('@module.builtin.lua', { fg = '#75228e' })
    set_hl('@diff.delta', { link = 'diffChanged' })
    set_hl('@diff.minus', { link = 'diffRemoved' })
    set_hl('@lsp', {})
    set_hl('@lsp.type.class', { fg = '#75228e' })
    set_hl('@lsp.type.comment', { link = '@comment' })
    set_hl('@lsp.type.decorator', { link = '@attribute' })
    set_hl('@lsp.type.enum', { link = '@type' })
    set_hl('@lsp.type.enumMember', { link = '@constant' })
    set_hl('@lsp.type.event', { link = '@type' })
    set_hl('@lsp.type.function', { link = '@function' })
    set_hl('@lsp.type.interface', { link = '@interface' })
    set_hl('@lsp.type.keyword', { link = '@keyword' })
    set_hl('@lsp.type.macro', { link = '@constant.macro' })
    set_hl('@constant.macro', { link = 'Macro' })
    set_hl('@lsp.type.method', { link = '@function.method' })
    set_hl('@lsp.type.modifier', { link = '@type.qualifier' })
    set_hl('@type.qualifier', { fg = '#2c363c' })
    set_hl('@lsp.type.namespace', { link = '@namespace' })
    set_hl('@lsp.type.number', { link = '@number' })
    set_hl('@lsp.type.operator', { link = '@operator' })
    set_hl('@lsp.type.parameter', { link = '@variable.parameter' })
    set_hl('@lsp.type.property', {})
    set_hl('@lsp.type.regexp', { link = '@string.regexp' })
    set_hl('@lsp.type.string', { link = '@string' })
    set_hl('@lsp.type.struct', { link = '@type' })
    set_hl('@lsp.type.type', { link = '@type' })
    set_hl('@lsp.type.typeParameter', { link = '@type.definition' })
    set_hl('@lsp.type.variable', {})
    set_hl('@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
    set_hl('@markup', { link = 'Special' })
    set_hl('@markup.strong', { bold = true, fg = '#1f2328' })
    set_hl('@markup.italic', { italic = true, fg = '#1f2328' })
    set_hl('@markup.strikethrough', { strikethrough = true, fg = '#1f2328' })
    set_hl('@markup.underline', { underline = true })
    set_hl('@markup.heading', { link = 'Title' })
    set_hl('@markup.link', { underline = true, fg = '#1f2328' })
    set_hl('@diff', {})
    set_hl('@diff.plus', { link = 'diffAdded' })
    set_hl('@keyword', { link = 'Keyword' })
    set_hl('@punctuation', { link = 'Delimiter' })
    set_hl('@punctuation.special', { link = 'Special' })
    set_hl('@comment', { link = 'Comment' })
    set_hl('@comment.error', { fg = '#ffffff', bg = '#d1242f' })
    set_hl('@comment.warning', { fg = '#ffffff', bg = '#9a6700' })
    set_hl('@comment.note', { link = 'DiagnosticInfo' })
    set_hl('@comment.todo', { fg = '#ffffff', bg = '#d0d7de' })
    set_hl('@lsp.type.method.yaml.ansible', { fg = '#007070' })
    set_hl('@lsp.type.keyword.yaml.ansible', { fg = '#015493' })
    set_hl('@boolean.yaml', { bold = true })
    set_hl('@boolean.terraform', { bold = true })
    set_hl('@lsp.type.type.terraform', { fg = '#004c63' })
    set_hl('@lsp.mod.global.lua', { bold = true, fg = '#004c63' })
    set_hl('@boolean.lua', { bold = true })
    set_hl('@lsp.typemod.function.defaultLibrary.lua', { fg = '#75228e' })
    set_hl('@keyword.directive.jinja', { fg = '#8d5b00' })
    set_hl('@keyword.conditional.ternary.c', { bold = true, fg = '#8d5b00' })
    set_hl('@constant.builtin.c', { bold = true, fg = '#004c63' })
    set_hl('@boolean.python', { bold = true, fg = '#57606a' })
    set_hl('@lsp.typemod.class.builtin.python', { italic = true, fg = '#015493' })
    set_hl('@lsp.type.class.python', { fg = '#015493' })
    set_hl('lualine_a_replace', { fg = palette.normal, bg = palette.light.red })
    set_hl('@lsp.typemod.variable.defaultLibrary', { link = '@variable.builtin' })
    set_hl('@namespace', {})
    set_hl('@interface', {})
    set_hl('@string.special.symbol', { link = '@constant' })
    set_hl('@punctuation.bracket', { fg = '#2c363c' })
    set_hl('@comment.hint', { fg = '#ffffff', bg = '#d0d7de' })
    set_hl('@comment.info', { fg = '#ffffff', bg = palette.ansi.cyan })
    set_hl('@markup.environment', { fg = '#2c363c' })
    set_hl('@markup.environment.name', { fg = '#007070' })
    set_hl('@markup.link.uri', { underline = true, italic = true, fg = '#2c363c' })
    set_hl('@markup.link.label', { link = 'Special' })
    set_hl('@markup.raw', { italic = true, fg = '#2c363c' })
    set_hl('@markup.list', { fg = '#004c63' })
    set_hl('@markup.list.checked', { fg = '#116329' })
    set_hl('@markup.list.unchecked', { fg = '#57606a' })
    set_hl('@variable.member', { fg = '#2c363c' })
    set_hl('@tag.attribute', { link = '@variable.member' })
    set_hl('@tag.delimiter', {})
    set_hl('@none', { link = 'NONE' })
    set_hl('@conceal', { link = 'Conceal' })
    set_hl('@operator.bash', { fg = '#2c363c' })
    set_hl('@function.builtin.bash', { fg = '#2c363c' })
    set_hl('@function.call.bash', { fg = '#2c363c' })
    set_hl('@number.bash', {})
    set_hl('@punctuation.delimiter.bash', { fg = '#2c363c' })
    set_hl('@markup.list.bash', { link = '@punctuation.bash' })
    set_hl('@type.css', { link = 'htmlTag' })
    set_hl('@module.c_sharp', { fg = '#953800' })
    set_hl('@string.special.path.gitignore', { fg = '#6639ba' })
    set_hl('@module.go', {})
    set_hl('@markup.heading.html', { fg = '#1f2328' })
    set_hl('@constant.html', { link = '@tag' })
    set_hl('@tag.javascript', { link = '@type.javascript' })
    set_hl('@tag.tsx', { link = '@type.tsx' })
    set_hl('@tag.delimiter.javascript', { link = '@tag.attribute.javascript' })
    set_hl('@tag.delimiter.tsx', { link = '@tag.attribute.tsx' })
    set_hl('@property.json', { link = '@tag' })
    set_hl('@lsp.type.variable.lua', {})
    set_hl('@constructor.lua', { fg = '#2c363c' })
    set_hl('@operator.lua', { fg = '#2c363c' })
    set_hl('@property.lua', { fg = '#2c363c' })
    set_hl('@function.builtin.lua', { fg = '#75228e' })
    set_hl('@property.luadoc', { link = '@property.lua' })
    set_hl('@variable.member.luadoc', { link = '@property.luadoc' })
    set_hl('@operator.luadoc', { fg = '#1f2328' })
    set_hl('@markup.list.luadoc', { fg = '#1f2328' })
    set_hl('@string.special.symbol.make', { link = '@function' })
    set_hl('@function.builtin.make', { link = '@constant' })
    set_hl('@punctuation.delimiter.markdown', { fg = '#1f2328' })
    set_hl('@punctuation.delimiter.markdown_inline', { fg = '#1f2328' })
    set_hl('@markup.quote.markdown', { fg = '#015493' })
    set_hl('@variable.member.nix', { link = '@variable.member' })
    set_hl('@variable.parameter.nix', { link = '@variable.parameter' })
    set_hl('@string.special.path.nix', { link = '@string' })
    set_hl('@module.php', { link = '@constructor.php' })
    set_hl('@variable.member.python', { fg = '#1f2328' })
    set_hl('@type.builtin.python', { link = '@constant' })
    set_hl('@variable.builtin.python', { link = '@constant' })
    set_hl('@module.python', {})
    set_hl('@label.ruby', { fg = '#2c363c' })
    set_hl('@string.special.symbol.ruby', { link = '@constant' })
    set_hl('@module.elixir', { link = '@type' })
    set_hl('@constant.builtin.rust', { fg = '#953800' })
    set_hl('@module.rust', {})
    set_hl('@keyword.directive.rust', { fg = '#2c363c' })
    set_hl('@keyword.storage.lifetime.rust', { link = '@tag.rust' })
    set_hl('@keyword.storage.lifetime.punctuation.rust', { link = '@markup.list.rust' })
    set_hl('@property.scss', { link = '@constant' })
    set_hl('@variable.scss', { link = '@variable.parameter' })
    set_hl('@variable.member.sql', { link = '@constant' })
    set_hl('@type.sql', { link = '@variable' })
    set_hl('@variable.sql', { link = '@constant' })
    set_hl('@variable.parameter.vimdoc', { fg = '#953800' })
    set_hl('@label.vimdoc', { link = '@keyword' })
    set_hl('@property.yaml', { link = '@tag' })
    set_hl('@variable', { fg = '#2c363c' })
    set_hl('@variable.builtin', { fg = '#75228e' })
    set_hl('@variable.parameter', { fg = '#2c363c' })
    set_hl('@variable.parameter.builtin', { fg = '#75228e' })
    set_hl('@constant', { link = 'Constant' })
    set_hl('@constant.builtin', { bold = true, fg = '#004c63' })
    set_hl('@module', { fg = '#015493' })
    set_hl('@module.builtin', { fg = '#004c63' })
    set_hl('@label', { link = '@tag' })
    set_hl('@string', { link = 'String' })
    set_hl('@keyword.exception', { fg = '#75228e' })
    set_hl('@keyword.function', { bold = true, fg = '#2c363c' })
    set_hl('@keyword.operator', { fg = '#75228e' })
    set_hl('@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })
    set_hl('@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
    set_hl('@lsp.typemod.operator.injected', { link = '@operator' })
    set_hl('@lsp.typemod.string.injected', { link = '@string' })
    set_hl('@lsp.typemod.variable.injected', { link = '@variable' })
    set_hl('@string.regexp', { fg = '#8d5b00' })
    set_hl('@string.special', { link = 'SpecialChar' })
    set_hl('@string.escape', { fg = '#8d5b00' })
    set_hl('@string.special.url', { underline = true, italic = true, fg = '#2c363c' })
    set_hl('@character', { link = 'Character' })
    set_hl('@character.special', { link = 'SpecialChar' })
    set_hl('@boolean', { link = 'Boolean' })
    set_hl('@number', { link = 'Number' })
    set_hl('@number.float', { link = 'Float' })
    set_hl('@type', { fg = '#004c63' })
    set_hl('@type.builtin', { italic = true, fg = '#015493' })
    set_hl('@attribute', { link = 'Constant' })
    set_hl('@attribute.builtin', { link = 'Special' })
    set_hl('@property', { link = '@variable.member' })
    set_hl('Identifier', { fg = '#2c363c' })
    set_hl('@function', { link = 'Function' })
    set_hl('@function.builtin', { fg = '#75228e' })
    set_hl('@constructor', { fg = '#75228e' })
    set_hl('@operator', { link = 'Operator' })
end

local function fzf_lua()
    set_hl('FzfLuaNormal', { link = 'Normal' })
    set_hl('FzfLuaBorder', { link = 'Normal' })
    set_hl('FzfLuaCursor', { link = 'Cursor' })
    set_hl('FzfLuaCursorLine', { link = 'CursorLine' })
    set_hl('FzfLuaCursorLineNr', { link = 'CursorLineNr' })
    set_hl('FzfLuaSearch', { link = 'IncSearch' })
    set_hl('FzfLuaTitle', { link = 'Title' })
    set_hl('FzfLuaScrollBorderEmpty', { link = 'FzfLuaBorder' })
    set_hl('FzfLuaHelpBorder', { link = 'FzfLuaBorder' })
    set_hl('FzfLuaScrollFloatFull', { link = 'PmenuThumb' })
    set_hl('FzfLuaScrollFloatEmpty', { link = 'PmenuSbar' })
    set_hl('FzfLuaScrollBorderFull', { link = 'FzfLuaBorder' })
    set_hl('FzfLuaHelpNormal', { link = 'FzfLuaNormal' })
end

set_hl('TreesitterContext', { bg = '#dfdfe1' })
set_hl('MiniHipatternsFixme', { fg = palette.normal, bg = palette.light.red })
set_hl('MiniHipatternsHack', { fg = palette.normal, bg = palette.light.yellow })
set_hl('WhichKeyGroup', { link = 'Function' })
set_hl('MiniHipatternsTodo', { fg = palette.normal, bg = palette.light.green })
set_hl('WhichKeySeperator', { link = 'Comment' })
set_hl('WhichKeySeparator', { link = 'Comment' })
set_hl('MiniHipatternsNote', { fg = palette.normal, bg = palette.light.blue })
set_hl('WhichKeyValue', { link = 'Comment' })
set_hl('MiniCursorwordCurrent', { bg = palette.extra.cursorWord })
set_hl('MiniCursorword', { bg = palette.extra.cusorWord })
set_hl('MiniPickMatchRanges', { fg = palette.normal, bg = palette.light.yellow })
set_hl('FidgetTitle', { link = 'Title' })
set_hl('MiniPickPrompt', { fg = '#2c363c' })
set_hl('Bold', { bold = true })
set_hl('GitGutterAdd', { fg = '#1a7f37' })
set_hl('GitGutterChange', { fg = '#9a6700' })
set_hl('GitGutterDelete', { fg = '#d1242f' })
set_hl('GitSignsAdd', { fg = '#1a7f37' })
set_hl('GitSignsDelete', { fg = '#d1242f' })
set_hl('LspTroubleText', { fg = '#32383f' })
set_hl('LspTroubleCount', { fg = '#8250df', bg = '#57606a' })
set_hl('LspTroubleNormal', { fg = '#57606a', bg = '#f6f8fa' })
set_hl('MiniAnimateCursor', { reverse = true, nocombine = true })
set_hl('MiniAnimateNormalFloat', { link = 'NormalFloat' })
set_hl('MiniClueBorder', { link = 'FloatBorder' })
set_hl('MiniClueDescGroup', { link = 'DiagnosticFloatingWarn' })
set_hl('MiniClueDescSingle', { link = 'NormalFloat' })
set_hl('MiniClueNextKey', { fg = palette.ansi.cyan })
set_hl('MiniClueNextKeyWithPostkeys', { link = 'DiagnosticFloatingError' })
set_hl('MiniClueSeparator', { fg = '#d0d7de' })
set_hl('MiniClueTitle', { link = 'FloatTitle' })
set_hl('xmlTagName', { link = 'htmlTag' })
set_hl('MiniDiffSignAdd', { fg = '#1a7f37' })
set_hl('cssMedia', { link = 'Keyword' })
set_hl('cssProp', { link = 'Constant' })
set_hl('cssPseudoClassId', { link = 'Function' })
set_hl('lessAmpersand', { link = 'Function' })
set_hl('lessClass', { link = 'Function' })
set_hl('lessClassCall', { link = 'Function' })
set_hl('lessCssAttribute', { link = 'Constant' })
set_hl('lessFunction', { link = 'Constant' })
set_hl('lessVariable', { fg = '#1f2328' })
set_hl('diffOldFile', { fg = '#9a6700' })
set_hl('MiniFilesNormal', { link = 'NormalFloat' })
set_hl('MiniFilesTitle', { link = 'FloatTitle' })
set_hl('MiniFilesTitleFocused', { bold = true, fg = '#1f2328' })
set_hl('diffIndexLine', { fg = '#2c363c' })
set_hl('jsonKeyword', { fg = '#015493' })
set_hl('jsonNull', { link = 'Constant' })
set_hl('luaFunction', { link = 'Keyword' })
set_hl('luaTable', {})
set_hl('yamlBlockMappingKey', { fg = '#015493' })
set_hl('yamlFlowMappingKey', { fg = '#015493' })
set_hl('MiniMapNormal', { link = 'NormalFloat' })
set_hl('MiniMapSymbolCount', { link = 'Special' })
set_hl('MiniMapSymbolLine', { fg = palette.ansi.cyan })
set_hl('MiniMapSymbolView', { fg = '#bbdfff' })
set_hl('MiniOperatorsExchangeFrom', { link = 'IncSearch' })
set_hl('MiniPickBorder', { link = 'FloatBorder' })
set_hl('MiniPickBorderBusy', { link = 'DiagnosticFloatingWarn' })
set_hl('MiniPickBorderText', { link = 'FloatTitle' })
set_hl('MiniPickIconDirectory', { link = 'Directory' })
set_hl('MiniPickNormal', { link = 'NormalFloat' })
set_hl('MiniPickIconFile', { link = 'MiniPickNormal' })
set_hl('MiniPickMatchCurrent', { link = 'CursorLine' })
set_hl('MiniPickMatchMarked', { link = 'Visual' })
set_hl('CmpItemAbbr', { fg = '#1f2328' })
set_hl('CmpItemAbbrDeprecated', { strikethrough = true, fg = '#2c363c' })
set_hl('CmpItemAbbrMatch', { fg = '#007070' })
set_hl('CmpItemAbbrMatchFuzzy', { fg = '#007070' })
set_hl('CmpItemKindDefault', { fg = '#32383f' })
set_hl('CmpItemMenu', { link = 'Comment' })
set_hl('CmpItemKindKeyword', { link = 'Keyword' })
set_hl('CmpItemKindVariable', { link = '@variable' })
set_hl('CmpItemKindConstant', { link = '@constant' })
set_hl('CmpItemKindReference', { link = 'Keyword' })
set_hl('CmpItemKindValue', { link = 'Keyword' })
set_hl('CmpItemKindFunction', { link = 'Function' })
set_hl('CmpItemKindMethod', { link = 'Function' })
set_hl('CmpItemKindConstructor', { link = '@constructor' })
set_hl('CmpItemKindInterface', { link = 'Constant' })
set_hl('CmpItemKindEvent', { link = 'Constant' })
set_hl('CmpItemKindEnum', { link = 'Constant' })
set_hl('CmpItemKindUnit', { link = 'Constant' })
set_hl('CmpItemKindClass', { link = 'Type' })
set_hl('CmpItemKindStruct', { link = 'Type' })
set_hl('CmpItemKindModule', { link = '@module' })
set_hl('CmpItemKindProperty', { link = '@property' })
set_hl('CmpItemKindField', { link = '@variable.member' })
set_hl('CmpItemKindTypeParameter', { link = '@variable.member' })
set_hl('CmpItemKindEnumMember', { link = '@variable.member' })
set_hl('CmpItemKindOperator', { link = 'Operator' })
set_hl('CmpItemKindSnippet', { fg = '#32383f' })
set_hl('CocInlayHint', { fg = '#57606a', bg = '#f1f1f2' })
set_hl('CocExplorerNormalFloat', { link = 'NormalSB' })
set_hl('CocExplorerFileRootName', { bold = true, fg = '#1f2328' })
set_hl('CocExplorerFileDirectory', { bold = true, fg = '#1f2328' })
set_hl('CocExplorerGitPathChange_Internal', { fg = '#8250df' })
set_hl('CocExplorerGitAdded', { fg = '#1a7f37' })
set_hl('CocExplorerGitModified', { fg = '#9a6700' })
set_hl('CocExplorerGitContentChange', { fg = '#9a6700' })
set_hl('CocExplorerGitPathChange', { fg = '#8250df' })
set_hl('CocExplorerGitIgnored', { fg = '#57606a' })
set_hl('CocExplorerGitUntracked', { fg = '#57606a' })
set_hl('DapUIScope', { fg = '#1b7c83' })
set_hl('DapUIType', { fg = '#8250df' })
set_hl('DapUIModifiedValue', { bold = true, fg = '#1b7c83' })
set_hl('DapUIDecoration', { link = 'DapUIScope' })
set_hl('DapUIThread', { bold = true, fg = '#116329' })
set_hl('DapUIStoppedThread', { link = 'DapUIScope' })
set_hl('DapUISource', { link = 'DapUIType' })
set_hl('DapUILineNumber', { link = 'DapUIScope' })
set_hl('DapUIFloatBorder', { link = 'DapUIScope' })
set_hl('DapUIWatchesEmpty', { fg = '#cf222e' })
set_hl('DapUIWatchesValue', { fg = '#116329' })
set_hl('DapUIWatchesError', { link = 'DapUIWatchesEmpty' })
set_hl('DapUIBreakpointsPath', { link = 'DapUIScope' })
set_hl('DapUIBreakpointsInfo', { link = 'DapUIWatchesValue' })
set_hl('DapUIBreakpointsCurrentLine', { link = 'DapUIThread' })
set_hl('DapUIBreakpointsDisabledLine', { fg = '#6e7781' })
set_hl('DapUIStepOver', { link = 'DapUIScope' })
set_hl('DapUIStepInto', { link = 'DapUIScope' })
set_hl('DapUIStepBack', { link = 'DapUIScope' })
set_hl('DapUIStepOut', { link = 'DapUIScope' })
set_hl('DapUIStop', { link = 'DapUIWatchesEmpty' })
set_hl('DapUIPlayPause', { link = 'DapUIWatchesValue' })
set_hl('DapUIRestart', { link = 'DapUIWatchesValue' })
set_hl('DapUIUnavailable', { link = 'DapUIBreakpointsDisabledLine' })
set_hl('DapUIWinSelect', { link = 'DapUIModifiedValue' })
set_hl('DashboardShortCut', { link = 'Identifier' })
set_hl('DashboardHeader', { link = 'Title' })
set_hl('DashboardCenter', { link = 'String' })
set_hl('DashboardFooter', { italic = true, fg = '#2c363c' })
set_hl('WhichKeyFloat', { bg = '#f6f8fa' })
set_hl('WhichKeyDesc', { link = 'Keyword' })
set_hl('WhichKey', { link = 'Identifier' })
set_hl('MiniDiffSignDelete', { fg = '#d1242f' })
set_hl('MiniDiffSignChange', { fg = '#9a6700' })
set_hl('MiniJump2dSpot', { bold = true, fg = '#a40e26' })
set_hl('MiniJump2dSpotUnique', { bold = true, fg = '#9a6700' })
set_hl('MiniPickHeader', { fg = '#004c63' })
set_hl('MiniJump', { link = 'SpellRare' })
set_hl('cssBraces', { fg = '#2c363c' })
set_hl('MiniDiffOverContext', { link = 'DiffChange' })
set_hl('MiniCompletionActiveParameter', { underline = true })
set_hl('CmpDocumentation', { fg = '#1f2328', bg = '#f6f8fa' })
set_hl('SignColumnSB', { link = 'SignColumn' })
set_hl('diffLine', { fg = '#004c63' })
set_hl('FidgetTask', { link = 'LineNr' })
set_hl('IndentBlanklineContextStart', { underline = true, sp = '#fb8f44' })
set_hl('IndentBlanklineContextChar', { fg = '#b7d9e1' })
set_hl('IndentBlanklineChar', { fg = '#e9e9ea' })
set_hl('GitSignsChange', { fg = '#9a6700' })
set_hl('Italic', { italic = true })
set_hl('qfLineNr', { link = 'LineNr' })
set_hl('qfFileName', { link = 'Directory' })
set_hl('xmlAttrib', { link = 'htmlTag' })
set_hl('diffNewFile', { fg = '#d0d7de' })
set_hl('diffFile', { fg = palette.ansi.cyan })
set_hl('MiniFilesDirectory', { link = 'Directory' })
set_hl('MiniFilesBorder', { link = 'FloatBorder' })
set_hl('MiniFilesBorderModified', { link = 'DiagnosticFloatingWarn' })
set_hl('MiniIndentscopeSymbol', { link = 'Delimiter' })
set_hl('MiniJump2dSpotAhead', { nocombine = true, fg = palette.ansi.cyan })
set_hl('MiniFilesCursorLine', { link = 'CursorLine' })
set_hl('CmpDocumentationBorder', { fg = '#dae9f9', bg = '#f6f8fa' })
set_hl('MiniFilesFile', { fg = '#1f2328' })
set_hl('MiniJump2dDim', { link = 'Comment' })
set_hl('MiniIndentscopePrefix', { nocombine = true })
set_hl('MiniDiffOverChange', { fg = '#1f2328', bg = '#e7eaf0' })
set_hl('MiniDiffOverDelete', { link = 'DiffDelete' })
set_hl('MiniDiffOverAdd', { link = 'DiffAdd' })
set_hl('MiniPickPromptCaret', { fg = '#a1a1a1' })
set_hl('MiniPickPromptPrefix', { fg = '#a1a1a1' })
set_hl('BlinkCmpMenu', { bg = '#d1d1d1' })
set_hl('BlinkCmpKindText', { fg = '#2c363c' })
set_hl('BlinkCmpLabelMatch', { fg = '#2c363c', bg = '#e1d1b3' })
set_hl('BlinkCmpSignatureHelp', { fg = '#75228e', bg = '#d1d1d1' })
set_hl('BlinkCmpSignatureHelpBorder', { fg = '#007070', bg = '#d1d1d1' })
set_hl('BlinkCmpSignatureHelpActiveParameter', { fg = '#b81a6b', bg = '#d1d1d1' })
set_hl('GitSignsChangedelete', { link = 'GitSignsChange' })
set_hl('GitSignsTopdelete', { link = 'GitSignsDelete' })
set_hl('GitSignsUntracked', { link = 'GitSignsAdd' })
set_hl('GitSignsAddNr', { link = 'GitSignsAdd' })
set_hl('GitGutterAddLineNr', {})
set_hl('GitSignsChangeNr', { link = 'GitSignsChange' })
set_hl('GitGutterChangeLineNr', {})
set_hl('GitSignsDeleteNr', { link = 'GitSignsDelete' })
set_hl('GitGutterDeleteLineNr', {})
set_hl('GitSignsChangedeleteNr', { link = 'GitSignsChangeNr' })
set_hl('GitSignsTopdeleteNr', { link = 'GitSignsDeleteNr' })
set_hl('GitSignsUntrackedNr', { link = 'GitSignsAddNr' })
set_hl('GitSignsAddLn', { link = 'DiffAdd' })
set_hl('GitGutterAddLine', {})
set_hl('SignifyLineAdd', {})
set_hl('GitSignsChangeLn', { link = 'DiffChange' })
set_hl('GitGutterChangeLine', {})
set_hl('SignifyLineChange', {})
set_hl('GitSignsChangedeleteLn', { link = 'GitSignsChangeLn' })
set_hl('GitSignsTopdeleteLn', { link = 'GitSignsDeleteLn' })
set_hl('GitSignsDeleteLn', {})
set_hl('GitSignsUntrackedLn', { link = 'GitSignsAddLn' })
set_hl('GitSignsAddCul', { link = 'GitSignsAdd' })
set_hl('GitSignsChangeCul', { link = 'GitSignsChange' })
set_hl('GitSignsDeleteCul', { link = 'GitSignsDelete' })
set_hl('GitSignsChangedeleteCul', { link = 'GitSignsChangeCul' })
set_hl('GitSignsTopdeleteCul', { link = 'GitSignsDeleteCul' })
set_hl('GitSignsUntrackedCul', { link = 'GitSignsAddCul' })
set_hl('GitSignsStagedAdd', { fg = '#8cbf9b' })
set_hl('GitSignsStagedChange', { fg = '#ccb37f' })
set_hl('GitSignsStagedDelete', { fg = '#e89197' })
set_hl('GitSignsStagedChangedelete', { fg = '#ccb37f' })
set_hl('GitSignsStagedTopdelete', { fg = '#e89197' })
set_hl('GitSignsStagedUntracked', { fg = '#8cbf9b' })
set_hl('GitSignsStagedAddNr', { fg = '#8cbf9b' })
set_hl('GitSignsStagedChangeNr', { fg = '#ccb37f' })
set_hl('GitSignsStagedDeleteNr', { fg = '#e89197' })
set_hl('GitSignsStagedChangedeleteNr', { fg = '#ccb37f' })
set_hl('GitSignsStagedTopdeleteNr', { fg = '#e89197' })
set_hl('GitSignsStagedUntrackedNr', { fg = '#8cbf9b' })
set_hl('GitSignsStagedAddLn', { fg = '#8cbf9b', bg = '#b8d0bf' })
set_hl('GitSignsStagedChangeLn', { fg = '#ccb37f', bg = '#d8cab3' })
set_hl('GitSignsStagedChangedeleteLn', { fg = '#ccb37f', bg = '#d8cab3' })
set_hl('GitSignsStagedTopdeleteLn', {})
set_hl('GitSignsStagedUntrackedLn', { fg = '#8cbf9b', bg = '#b8d0bf' })
set_hl('GitSignsStagedAddCul', { fg = '#8cbf9b' })
set_hl('GitSignsStagedChangeCul', { fg = '#ccb37f' })
set_hl('GitSignsStagedDeleteCul', { fg = '#e89197' })
set_hl('GitSignsStagedChangedeleteCul', { fg = '#ccb37f' })
set_hl('GitSignsStagedTopdeleteCul', { fg = '#e89197' })
set_hl('GitSignsStagedUntrackedCul', { fg = '#8cbf9b' })
set_hl('GitSignsAddPreview', { link = 'DiffAdd' })
set_hl('GitSignsDeletePreview', { link = 'DiffDelete' })
set_hl('GitGutterDeleteLine', {})
set_hl('SignifyLineDelete', {})
set_hl('GitSignsNoEOLPreview', { link = 'Constant' })
set_hl('DiffNoEOL', {})
set_hl('GitSignsCurrentLineBlame', { link = 'NonText' })
set_hl('GitSignsAddInline', { link = 'TermCursor' })
set_hl('GitSignsDeleteInline', { link = 'TermCursor' })
set_hl('GitSignsChangeInline', { link = 'TermCursor' })
set_hl('GitSignsAddLnInline', { link = 'GitSignsAddInline' })
set_hl('GitSignsChangeLnInline', { link = 'GitSignsChangeInline' })
set_hl('GitSignsDeleteLnInline', { link = 'GitSignsDeleteInline' })
set_hl('GitSignsDeleteVirtLn', { link = 'DiffDelete' })
set_hl('GitSignsDeleteVirtLnInLine', { link = 'GitSignsDeleteLnInline' })
set_hl('GitSignsVirtLnum', { link = 'GitSignsDeleteVirtLn' })
set_hl('TreesitterContextLineNumber', { bg = '#dfdfe1' })
set_hl('TreesitterContextBottom', { underline = true, sp = '#d9d9d9' })
set_hl('TreesitterContextLineNumberBottom', { underline = true, sp = '#d9d9d9' })
set_hl('TreesitterContextSeparator', { link = 'FloatBorder' })
set_hl('CodeCompanionChatInfo', { link = 'DiagnosticInfo' })
set_hl('CodeCompanionChatError', { link = 'DiagnosticError' })
set_hl('CodeCompanionChatWarn', { link = 'DiagnosticWarn' })
set_hl('CodeCompanionChatSubtext', { link = 'Comment' })
set_hl('CodeCompanionChatFold', { link = '@markup.quote.markdown' })
set_hl('CodeCompanionChatHeader', { link = '@markup.heading.2.markdown' })
set_hl('CodeCompanionChatSeparator', { link = '@punctuation.special.markdown' })
set_hl('CodeCompanionChatTokens', { link = 'Comment' })
set_hl('CodeCompanionChatTool', { link = 'Special' })
set_hl('CodeCompanionChatToolFailure', { link = 'DiagnosticError' })
set_hl('CodeCompanionChatToolFailureIcon', { link = 'Error' })
set_hl('CodeCompanionChatToolGroup', { link = 'Constant' })
set_hl('CodeCompanionChatToolInProgress', { link = 'DiagnosticInfo' })
set_hl('CodeCompanionChatToolInProgressIcon', { link = 'DiagnosticInfo' })
set_hl('CodeCompanionChatToolPending', { link = 'DiagnosticWarn' })
set_hl('CodeCompanionChatToolPendingIcon', { link = 'DiagnosticWarn' })
set_hl('CodeCompanionChatToolSuccess', { link = 'DiagnosticOk' })
set_hl('CodeCompanionChatToolSuccessIcon', { link = 'DiagnosticOk' })
set_hl('CodeCompanionChatVariable', { link = 'Identifier' })
set_hl('CodeCompanionChatInfoBanner', { link = 'WildMenu' })
set_hl('CodeCompanionVirtualText', { link = 'Comment' })
set_hl('CodeCompanionInlineDiffHint', { bg = '#d1d1d1' })
set_hl('CopilotAnnotation', { link = 'Comment' })
set_hl('CopilotSuggestion', { link = 'Comment' })
set_hl('HoverFloatingError', { link = 'DiagnosticFloatingError' })
set_hl('HoverFloatingWarn', { link = 'DiagnosticFloatingWarn' })
set_hl('HoverFloatingInfo', { link = 'DiagnosticFloatingInfo' })
set_hl('HoverFloatingHint', { link = 'DiagnosticFloatingHint' })
set_hl('HoverWindow', { link = 'NormalFloat' })
set_hl('HoverBorder', { link = 'FloatBorder' })
set_hl('HoverSourceLine', { link = 'TabLine' })
set_hl('HoverActiveSource', { link = 'TabLineSel' })
set_hl('HoverInactiveSource', { link = 'TabLineFill' })

local function rainbow()
    set_hl('RainbowRed', { fg = '#d1d1d1' })
    set_hl('RainbowYellow', { fg = '#d1d1d1' })
    set_hl('RainbowBlue', { fg = '#d1d1d1' })
    set_hl('RainbowOrange', { fg = '#d1d1d1' })
    set_hl('RainbowGreen', { fg = '#d1d1d1' })
    set_hl('RainbowViolet', { fg = '#d1d1d1' })
    set_hl('RainbowCyan', { fg = '#d1d1d1' })

    set_hl('RainbowDelimiterRed', { fg = '#cc241d' })
    set_hl('RainbowDelimiterOrange', { fg = '#d65d0e' })
    set_hl('RainbowDelimiterYellow', { fg = '#d79921' })
    set_hl('RainbowDelimiterGreen', { fg = '#689d6a' })
    set_hl('RainbowDelimiterCyan', { fg = '#a89984' })
    set_hl('RainbowDelimiterBlue', { fg = '#458588' })
    set_hl('RainbowDelimiterViolet', { fg = '#b16286' })
end

local function indent_blankline()
    set_hl('IblIndent', { fg = '#e7eaf0' })
    set_hl('IblWhitespace', { fg = '#e7eaf0' })
    set_hl('IblScope', { fg = '#6e7781' })
    set_hl('@ibl', {})
    set_hl('@ibl.indent.char.1', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.indent.char.2', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.indent.char.3', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.indent.char.4', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.indent.char.5', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.indent.char.6', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.indent.char.7', { nocombine = true, fg = '#d1d1d1' })
    set_hl('@ibl.whitespace.char.1', { nocombine = true, fg = '#e7eaf0' })
    set_hl('@ibl.scope.char.1', { nocombine = true, fg = '#6e7781' })
    set_hl('@ibl.scope.underline.1', { underline = true, sp = '#6e7781' })
end

local function blink_cmp()
    set_hl('BlinkCmpLabel', { link = 'CmpItemAbbr' })
    set_hl('BlinkCmpLabelDeprecated', { link = 'CmpItemAbbrDeprecated' })
    set_hl('BlinkCmpLabelDetail', { link = 'CmpItemMenu' })
    set_hl('BlinkCmpLabelDescription', { link = 'CmpItemMenu' })
    set_hl('CmpItemKind', {})
    set_hl('BlinkCmpKind', { link = 'CmpItemKind' })
    set_hl('BlinkCmpSource', { link = 'CmpItemMenu' })
    set_hl('CmpItemKindText', {})
    set_hl('BlinkCmpKindMethod', { link = 'CmpItemKindMethod' })
    set_hl('BlinkCmpKindFunction', { link = 'CmpItemKindFunction' })
    set_hl('BlinkCmpKindConstructor', { link = 'CmpItemKindConstructor' })
    set_hl('BlinkCmpKindField', { link = 'CmpItemKindField' })
    set_hl('BlinkCmpKindVariable', { link = 'CmpItemKindVariable' })
    set_hl('BlinkCmpKindClass', { link = 'CmpItemKindClass' })
    set_hl('BlinkCmpKindInterface', { link = 'CmpItemKindInterface' })
    set_hl('BlinkCmpKindModule', { link = 'CmpItemKindModule' })
    set_hl('BlinkCmpKindProperty', { link = 'CmpItemKindProperty' })
    set_hl('BlinkCmpKindUnit', { link = 'CmpItemKindUnit' })
    set_hl('BlinkCmpKindValue', { link = 'CmpItemKindValue' })
    set_hl('BlinkCmpKindEnum', { link = 'CmpItemKindEnum' })
    set_hl('BlinkCmpKindKeyword', { link = 'CmpItemKindKeyword' })
    set_hl('BlinkCmpKindSnippet', { link = 'CmpItemKindSnippet' })
    set_hl('CmpItemKindColor', {})
    set_hl('BlinkCmpKindColor', { link = 'CmpItemKindColor' })
    set_hl('CmpItemKindFile', {})
    set_hl('BlinkCmpKindFile', { link = 'CmpItemKindFile' })
    set_hl('BlinkCmpKindReference', { link = 'CmpItemKindReference' })
    set_hl('CmpItemKindFolder', {})
    set_hl('BlinkCmpKindFolder', { link = 'CmpItemKindFolder' })
    set_hl('BlinkCmpKindEnumMember', { link = 'CmpItemKindEnumMember' })
    set_hl('BlinkCmpKindConstant', { link = 'CmpItemKindConstant' })
    set_hl('BlinkCmpKindStruct', { link = 'CmpItemKindStruct' })
    set_hl('BlinkCmpKindEvent', { link = 'CmpItemKindEvent' })
    set_hl('BlinkCmpKindOperator', { link = 'CmpItemKindOperator' })
    set_hl('BlinkCmpKindTypeParameter', { link = 'CmpItemKindTypeParameter' })
    set_hl('BlinkCmpScrollBarThumb', { link = 'PmenuThumb' })
    set_hl('BlinkCmpScrollBarGutter', { link = 'PmenuSbar' })
    set_hl('CmpGhostText', {})
    set_hl('BlinkCmpGhostText', { link = 'CmpGhostText' })
    set_hl('BlinkCmpMenuBorder', { link = 'Pmenu' })
    set_hl('BlinkCmpMenuSelection', { link = 'PmenuSel' })
    set_hl('BlinkCmpDoc', { link = 'NormalFloat' })
    set_hl('BlinkCmpDocBorder', { link = 'NormalFloat' })
    set_hl('BlinkCmpDocSeparator', { link = 'NormalFloat' })
    set_hl('BlinkCmpDocCursorLine', { link = 'Visual' })
end

lualine()
treesitter()
blink_cmp()
rainbow()
mini()
fzf_lua()
default()
