local palette = require("palette")

local function set_hl(group, options)
    local hl = vim.api.nvim_set_hl
    hl(0, group, options)
end

set_hl('lualine_transparent', { fg = palette.normal })
set_hl('lualine_b_command', { fg = palette.normal })
set_hl('lualine_a_command', { fg = palette.normal })
set_hl('lualine_c_command', { fg = palette.normal })
set_hl('lualine_b_terminal', { fg = palette.normal })
set_hl('lualine_a_terminal', { fg = palette.normal })
set_hl('lualine_c_terminal', { fg = palette.normal })
set_hl('lualine_b_normal', { fg = palette.normal })
set_hl('lualine_a_normal', { fg = palette.normal })
set_hl('lualine_c_normal', { fg = palette.normal })
set_hl('lualine_b_visual', { fg = palette.normal, bg = palette.light.blue })
set_hl('lualine_a_visual', { fg = palette.normal, bg = palette.light.blue })
set_hl('lualine_c_visual', { fg = palette.normal, bg = palette.light.blue })
set_hl('lualine_b_replace', { fg = palette.normal, bg = palette.light.red })
set_hl('lualine_a_replace', { fg = palette.normal, bg = palette.light.red })
set_hl('lualine_c_replace', { fg = palette.normal, bg = palette.light.red })
set_hl('lualine_b_insert', { fg = palette.normal, bg = palette.light.green })
set_hl('lualine_a_insert', { fg = palette.normal, bg = palette.light.green })
set_hl('lualine_c_insert', { fg = palette.normal, bg = palette.light.green })
set_hl('lualine_b_inactive', { fg = palette.normal })
set_hl('lualine_a_inactive', { fg = palette.normal })
set_hl('lualine_c_inactive', { fg = palette.normal })
set_hl('lualine_b_diff_added_normal', { fg = '#1a7f37' })
set_hl('lualine_b_diff_added_insert', { fg = '#1a7f37', bg = '#d7e6dd' })
set_hl('lualine_b_diff_added_visual', { fg = '#1a7f37', bg = '#d3e4f1' })
set_hl('lualine_b_diff_added_replace', { fg = '#1a7f37', bg = '#f4d8e4' })
set_hl('lualine_b_diff_added_command', { fg = '#1a7f37' })
set_hl('lualine_b_diff_added_terminal', { fg = '#1a7f37' })
set_hl('lualine_b_diff_added_inactive', { fg = '#1a7f37' })
set_hl('lualine_b_diff_modified_normal', { fg = '#9a6700' })
set_hl('lualine_b_diff_modified_insert', { fg = '#9a6700', bg = '#d7e6dd' })
set_hl('lualine_b_diff_modified_visual', { fg = '#9a6700', bg = '#d3e4f1' })
set_hl('lualine_b_diff_modified_replace', { fg = '#9a6700', bg = '#f4d8e4' })
set_hl('lualine_b_diff_modified_command', { fg = '#9a6700' })
set_hl('lualine_b_diff_modified_terminal', { fg = '#9a6700' })
set_hl('lualine_b_diff_modified_inactive', { fg = '#9a6700' })
set_hl('lualine_b_diff_removed_normal', { fg = '#d1242f' })
set_hl('lualine_b_diff_removed_insert', { fg = '#d1242f', bg = '#d7e6dd' })
set_hl('lualine_b_diff_removed_visual', { fg = '#d1242f', bg = '#d3e4f1' })
set_hl('lualine_b_diff_removed_replace', { fg = '#d1242f', bg = '#f4d8e4' })
set_hl('lualine_b_diff_removed_command', { fg = '#d1242f' })
set_hl('lualine_b_diff_removed_terminal', { fg = '#d1242f' })
set_hl('lualine_b_diff_removed_inactive', { fg = '#d1242f' })
set_hl('lualine_x_diagnostics_error_normal', { fg = '#d1242f' })
set_hl('lualine_x_diagnostics_error_insert', { fg = '#d1242f', bg = '#d7e6dd' })
set_hl('lualine_x_diagnostics_error_visual', { fg = '#d1242f', bg = '#d3e4f1' })
set_hl('lualine_x_diagnostics_error_replace', { fg = '#d1242f', bg = '#f4d8e4' })
set_hl('lualine_x_diagnostics_error_command', { fg = '#d1242f' })
set_hl('lualine_x_diagnostics_error_terminal', { fg = '#d1242f' })
set_hl('lualine_x_diagnostics_error_inactive', { fg = '#d1242f' })
set_hl('lualine_x_diagnostics_warn_normal', { fg = '#9a6700' })
set_hl('lualine_x_diagnostics_warn_insert', { fg = '#9a6700', bg = '#d7e6dd' })
set_hl('lualine_x_diagnostics_warn_visual', { fg = '#9a6700', bg = '#d3e4f1' })
set_hl('lualine_x_diagnostics_warn_replace', { fg = '#9a6700', bg = '#f4d8e4' })
set_hl('lualine_x_diagnostics_warn_command', { fg = '#9a6700' })
set_hl('lualine_x_diagnostics_warn_terminal', { fg = '#9a6700' })
set_hl('lualine_x_diagnostics_warn_inactive', { fg = '#9a6700' })
set_hl('lualine_x_diagnostics_info_normal', { fg = '#0969da' })
set_hl('lualine_x_diagnostics_info_insert', { fg = '#0969da', bg = '#d7e6dd' })
set_hl('lualine_x_diagnostics_info_visual', { fg = '#0969da', bg = '#d3e4f1' })
set_hl('lualine_x_diagnostics_info_replace', { fg = '#0969da', bg = '#f4d8e4' })
set_hl('lualine_x_diagnostics_info_command', { fg = '#0969da' })
set_hl('lualine_x_diagnostics_info_terminal', { fg = '#0969da' })
set_hl('lualine_x_diagnostics_info_inactive', { fg = '#0969da' })
set_hl('lualine_x_diagnostics_hint_normal', { fg = '#007070' })
set_hl('lualine_x_diagnostics_hint_insert', { fg = '#007070', bg = '#d7e6dd' })
set_hl('lualine_x_diagnostics_hint_visual', { fg = '#007070', bg = '#d3e4f1' })
set_hl('lualine_x_diagnostics_hint_replace', { fg = '#007070', bg = '#f4d8e4' })
set_hl('lualine_x_diagnostics_hint_command', { fg = '#007070' })
set_hl('lualine_x_diagnostics_hint_terminal', { fg = '#007070' })
set_hl('lualine_x_diagnostics_hint_inactive', { fg = '#007070' })
