MiniDeps.add({ source = "folke/flash.nvim" })
MiniDeps.later(function()
    vim.keymap.set("n", "f", function()
        require("flash").jump()
    end, { desc = "Start flash jump mode", remap = true, silent = true })

    -- vim.keymap.set("n", "s", function()
    --     print("Not again!")
    -- end, { remap = true, silent = true })
end)
